README.md, doc/source/advancedexamples.rst, doc/source/examples.rst
I have corrected a few typos in code snippets in the docs. Also made minimal `import` changes and things like that so that if one is just looking at a particular section but has skipped the previous ones, everything is self-consistent. The latter are not strictly necessary, so as you prefer.
I have reviewed the "Basic examples" section and the "Advanced examples" up to QAOA (inclusive).
Two extra comments are:
- I think that `circuit depth` in the `summary` attribute of `Circuit` is actually referring to number of gates, rather than depth of the circuit, isn't it?
- This code snippet, extracted from the docs:
```
from qibo.models import Circuit
c = Circuit(3)
g0 = gates.RX(0, theta=0)
g1 = gates.RY(1, theta=0)
g2 = gates.fSim(0, 2, theta=0, phi=0)
c.add([g0, g1, …
```
=> Typos documentation

doc/source/examples.rst, doc/source/index.rst, src/qibo/__init__.py, src/qibo/base/circuit.py, src/qibo/tests/test_base.py, src/qibo/tests/test_density_matrix.py, src/qibo/tests/test_parametrized.py, src/qibo/tests/test_qasm.py, src/qibo/tests/test_qft.py
Implements the changes discussed in #238, particularly the following:
* Cast parameters given as a flat list to `circuit.set_parameters()` to `np.array` so that the snippet from #238 works.
* Change `circuit.depth` property to `circuit.ngates` as it returns the total number of gates in the circuit and not the depth.
* Create a new `circuit.depth` property that returns the actual depth, assuming that each gate is placed in the earliest possible position in the circuit according to the qubits it acts on. In order to do this calculation I extended the queue data structure slightly to hold a list of "moments" (in Cirq terminology).
* Change `circuit.summary` from `@property` to simple method so that it can be accessed as `circuit.summary()`.
* Update `circuit.summary()` to print both the …
=> Calculate correct circuit depth

setup.py, src/qibo/base/circuit.py, src/qibo/tests/test_qasm.py
Implements a very basic test for #244 using cirq.
This import qasm generated from Qibo in Cirq and compare the final wavefunction.
=> adding qibo to cirq qasm tests

doc/source/advancedexamples.rst, src/qibo/base/circuit.py, src/qibo/base/gates.py, src/qibo/tensorflow/distcircuit.py, src/qibo/tests/test_circuits.py
Closes #253 by implementing a `circuit.on_qubits(*q)` method on circuits that returns a generator of gates that exist in `circuit` acting on the specified `qubits`.
Example:
```Python
from qibo import models, gates
circuit = models.Circuit(8)
circuit.add(models.QFT(4).on_qubits(*range(0, 8, 2)))
circuit.add((gates.RX(i, theta=0) for i in range(8)))
circuit.add(models.QFT(4).invert().on_qubits(*range(1, 8, 2)))
```
Regarding the performance issue I mentioned in #253, I did some quick benchmarks on this on my local laptop. Particularly, I compare the above script with creating the QFT and inverse QFT gates with a custom generator from scratch (instead of using the QFT model and `on_qubits`). I see no difference in execution time, but as expected there is some difference in circuit creation …
=> Allow adding circuits to larger ones

doc/source/advancedexamples.rst
Following #238, this checks and proposes some updates in the remaining sections of the advanced examples in the docs. I checked the sections from QAOA until the end of advanced examples.
=> Remaining typos in advanced examples

src/qibo/config.py, src/qibo/tests/test_base.py, src/qibo/tests/test_gates.py
Currently `qibo.get_backend()` is returning `"custom"` regardless of the actual current backend because there is a confusion with the `'STRING'` and `'NAME'` dictionary keys for backends. Specifically `get_backend()` returns `'STRING'`, while `set_backend` updates `'NAME'`.
This PR removes the `'NAME'` key and updates `'STRING'` in `set_backend` so that everything works as expected.
=> Fix backend name returned by `qibo.get_backend()`

src/qibo/base/circuit.py, src/qibo/tests/test_cirq.py, src/qibo/tests/test_density_matrix.py, src/qibo/tests/test_qasm.py, src/qibo/tests/test_qft.py
Many thanks to @igres26 again for pointing out that the depth calculation was not correct. This PR fixes the issue and adds comparisons to depths calculated by Cirq in both `test_cirq.py` and `test_qasm.py` tests. 
If anyone has circuits available in either Qibo, Qasm or Cirq, we can cross-check that the depth calculated by Qibo agrees with Cirq in these cases as well.
=> Fix circuit depth calculation

.github/workflows/rules.yml, examples/conftest.py
Here we increase the `--examples-timeout` flag when testing examples. I have switched off these tests for macos because this can takes up to 4h, while the virtual machines for linux takes ~1h50min.
=> Increasing examples timeout

src/qibo/tensorflow/custom_operators/cc/kernels/apply_gate.h, src/qibo/tensorflow/custom_operators/cc/kernels/apply_gate_kernels.cc, src/qibo/tensorflow/custom_operators/cc/kernels/apply_gate_kernels.cu.cc
Replaces cudaMalloc/cudaFree with temporary Tensors.
=> Use tf primitives for GPU allocation

src/qibo/base/measurements.py, src/qibo/tensorflow/cgates.py, src/qibo/tensorflow/circuit.py, src/qibo/tensorflow/distcircuit.py
As discussed this removes the references to the state tensor before executing a circuit to avoid OOM errors when a circuit is executed multiple times on the same script. Note that if the user uses an additional reference to the final state (eg. `state = circuit()`, then `state` should also be deleted manually (`del(state)`) to avoid OOMs.
I tested this and it works when the default initial state is used. The situation is a bit more complicated when using a custom initial state. For example
```Python
initial_state = tf.zeros(2 ** nqubits, dtype=tf.complex128)
for i in range(nreps):
    initial_state = tf.zeros(2 ** nqubits, dtype=tf.complex128)
    state = circuit(initial_state)
    del(state)
```
works, however
```Python
for i in range(nreps):
    initial_state = tf.zeros(2 ** nqubits, …
```
=> Remove references to state vector to avoid OOM errors

doc/source/examples.rst, src/qibo/tensorflow/custom_operators/cc/kernels/apply_gate.h, src/qibo/tensorflow/custom_operators/cc/kernels/apply_gate_kernels.cc, src/qibo/tensorflow/custom_operators/cc/kernels/apply_gate_kernels.cu.cc, src/qibo/tensorflow/custom_operators/cc/ops/custom_ops.cc, src/qibo/tensorflow/custom_operators/python/ops/qibo_tf_custom_operators.py, src/qibo/tests/test_custom_operators.py
As discussed in #262 this implements the state normalization required in the Collapse gate within the custom kernel instead of using Tensorflow primitives. Performance is very close to using the tf norm:
nqubits | Collapse with tf norm | Collapse with custom norm 
-- | -- | --
27 | 0.56978 | 0.51419
28 | 1.06392 | 0.85471
29 | 2.01795 | 1.91229
30 | 4.01938 | 3.68727
31 | 7.89229 | 7.67427
32 | 15.8202 | 14.4606
however the custom norm is more stable in terms of RAM usage and uses the memory required for a single state copy. For example at 32 qubits double precision the custom norm uses 64GB, while the tf norm goes up to 120GB.
Currently the custom norm is implemented for CPU only and works with multi-threading. There are two issues to resolve (decide how to approach):
* Regarding GPU, …
=> Custom operator for normalization in Collapse gate

doc/source/advancedexamples.rst, doc/source/qibo.rst, src/qibo/base/circuit.py, src/qibo/base/gates.py, src/qibo/tensorflow/cgates.py, src/qibo/tensorflow/gates.py, src/qibo/tests/test_density_matrix.py, src/qibo/tests/test_gates.py
This implements two new channels: `ResetChannel` and `ThermalRelaxationChannel`, both following the corresponding [Qiskit implementation](https://qiskit.org/documentation/_modules/qiskit/providers/aer/noise/errors/standard_errors.html#thermal_relaxation_error). Note that the thermal relaxation channel, at least as it is implemented in Qiskit, is different depending on which of T1, T2 is larger. Specifically:
* If T1 >= T2 (which I think is the common case experimentally), the channel is a probabilistic mixture of unitaries and collapse gate so it can be implemented as a special case of `UnitaryChannel`. This case can also be simulated with state vectors and sampling.
* If T1 < T2 the channel is general (not a unitary mixture) and can only be used with density matrices. Qiskit uses the …
=> Thermal relaxation error channel

src/qibo/base/gates.py, src/qibo/config.py, src/qibo/tensorflow/cgates.py, src/qibo/tensorflow/custom_operators/cc/kernels/apply_gate_kernels.cc, src/qibo/tensorflow/gates.py, src/qibo/tensorflow/hamiltonians.py, src/qibo/tests/test_gates.py
Fixes some Collapse gate issues that I found while playing with the Shor example. Particularly the two following issues:
* Constructing the collapse gate fails when `result` is a `numpy` integer (eg. `np.int32`, `np.int64`) instead of pure Python `int`. I fixed this using the `NUMERIC_TYPES` we had in the Hamiltonians and added a relevant test.
* The C++ norm calculation is not working on a particular configuration of number of qubits and number of threads. For example using the collapse on 10 qubits on >35 threads is failing. This is because of a missing `+ 1` in the `nnorms` definition for the CPU custom operator. Things like that are a bit harder to capture in tests because most common machines and presumably the ones used by CI do not have that many threads.
=> Fix issues with Collapse gate

requirements.txt
Scipy is not a requirement of tf>=2.2 so we have to include it to the requirements list.
This issue is already visible in Qibo 0.1.1, however we didn't catch it because sphinx requires scipy.
=> adding scipy requirement

.github/workflows/rules.yml, .github/workflows/wheels.yml, doc/source/advancedexamples.rst, doc/source/installation.rst, requirements.txt, src/qibo/__init__.py, src/qibo/config.py, src/qibo/optimizers.py, src/qibo/tensorflow/cgates.py, src/qibo/tensorflow/custom_operators/Makefile, src/qibo/tensorflow/custom_operators/cc/kernels/apply_gate_kernels.cc, src/qibo/tensorflow/custom_operators/cc/kernels/transpose_state.cc, src/qibo/tensorflow/custom_operators/cc/ops/custom_ops.cc, src/qibo/tensorflow/custom_operators/python/ops/qibo_tf_custom_operators.py, src/qibo/tensorflow/distcircuit.py, src/qibo/tensorflow/distutils.py, src/qibo/tests/test_custom_operators.py, src/qibo/tests/test_vqe.py
This PR replace the TF thread pool mechanism with OpenMP.
This approach opens the possibility to:
- control the number of threads of each custom operator
- provides the `set_threads` and `get_threads` methods to set and get the number of threads. 
- by default we use the env variable OMP_NUM_THREADS, otherwise, if not set, we take the number of physical cores.
- adds a test for the parallel_L-BFGS-B optimizer
=> Replacing ThreadPool with OpenMP

.github/workflows/wheels.yml
This PR introduces a check for generated whl files. This also fixes the libomp dependency, now the user does not need to install libomp with homebrew before using Qibo.
There is an issue that has to be solved for linux https://github.com/pypa/manylinux/issues/836
=> testing wheels

doc/source/advancedexamples.rst, src/qibo/base/abstract_gates.py, src/qibo/base/circuit.py, src/qibo/base/gates.py, src/qibo/tensorflow/cgates.py, src/qibo/tensorflow/gates.py, src/qibo/tests/test_parametrized.py
This PR adds the `trainable` flag in all parametrized gates which allows the user to hide them from `circuit.get_parameters()` and `circuit.set_parameters()`. For example
```Python
c = Circuit(3)
c.add(gates.RX(0, theta=0))
c.add(gates.RY(1, theta=0.5, trainable=False))
c.add(gates.RZ(2, theta=0.8))
print(c.get_parameters()) 
c.set_parameters([0.2, 0.4])
```
@scarrazza, @igres26 I used the name `trainable` for this flag following Tensorflow/Keras but I am open to alternative suggestions.
=> Trainable flag for parametrized gates

src/qibo/tests/test_vqe.py
Fixes `test_vqe` crash on GPU when running the parallel l-bfgs-b.
=> Fix test failure on GPU for parallel lbfgs

doc/source/advancedexamples.rst, doc/source/qibo.rst, src/qibo/base/callbacks.py, src/qibo/tensorflow/callbacks.py, src/qibo/tensorflow/cgates.py, src/qibo/tensorflow/einsum.py, src/qibo/tests/test_callbacks.py, src/qibo/tests/test_density_matrix.py, src/qibo/tests/test_evolution.py
As part of the cleanup related to the backends this PR creates a `qibo.base.callbacks` module. So far we only had `qibo.tensorflow.callbacks` which was not consistent with the rest of the models. Also several methods from this file were independent of Tensorflow and thus can be moved to base.
=> Create base callbacks

.github/scripts/build-linux.sh, .github/workflows/wheels.yml
Here we update the wheels build procedure to include cuda 11. For simplicity I am launching the wheels action for all branches.
=> Updating wheels with cuda 11

src/qibo/tensorflow/circuit.py, src/qibo/tensorflow/custom_operators/cc/kernels/initial_state.h, src/qibo/tensorflow/custom_operators/cc/kernels/initial_state_kernels.cc, src/qibo/tensorflow/custom_operators/cc/kernels/initial_state_kernels.cu.cc, src/qibo/tensorflow/custom_operators/cc/ops/custom_ops.cc, src/qibo/tensorflow/distcircuit.py, src/qibo/tensorflow/distutils.py, src/qibo/tests/test_custom_operators.py
I am opening this PR to complement the implementation in #305 for GPU.
Now the code compiles and passes several tests on GPU, however there is something wrong with some of distributed circuit tests.
@stavros11 could you please have a look? Looks like the local state vectors are not recovered from the devices after applying gates, this may be due to the replacement of `.assign` with `=`.
=> custom initial_state GPU

src/qibo/tensorflow/circuit.py, src/qibo/tensorflow/custom_operators/cc/kernels/initial_state.h, src/qibo/tensorflow/custom_operators/cc/kernels/initial_state_kernels.cc, src/qibo/tensorflow/custom_operators/cc/kernels/initial_state_kernels.cu.cc, src/qibo/tensorflow/custom_operators/cc/ops/custom_ops.cc, src/qibo/tensorflow/distcircuit.py, src/qibo/tensorflow/distutils.py, src/qibo/tests/test_custom_operators.py
Following the discussion in #304 here I replace the tf.zeros with a full custom operator which builds our desired input state.
Interesting to note that we are faster than tf for small number of qubits while tf (eigen) wins for larger numbers.
Even if this PR solves the issue identified by @stavros11 for nqubits > 15, I have observed issues with the multiprocessing start method and openmp/tf-threadpool if we try to run code in parallel using more than 1 thread. For example, when setting `set_threads(2)` the multiprocessing run gets stuck silently. I have the suspicious that this is related to how the `fork` mode works, limiting the thread creation. 
I prefer to not merge this PR until I understand if the code can run in `spawn` mode. My only concern is about performance, the fork mode is …
=> custom initial_state

doc/source/qibo.rst, src/qibo/__init__.py, src/qibo/optimizers.py, src/qibo/parallel.py, src/qibo/tensorflow/circuit.py, src/qibo/tensorflow/custom_operators/cc/kernels/initial_state.h, src/qibo/tensorflow/custom_operators/cc/kernels/initial_state_kernels.cc, src/qibo/tensorflow/custom_operators/cc/kernels/initial_state_kernels.cu.cc, src/qibo/tensorflow/custom_operators/cc/ops/custom_ops.cc, src/qibo/tensorflow/distutils.py, src/qibo/tests/test_custom_operators.py, src/qibo/tests/test_parallel.py, src/qibo/tests/test_variational.py
This PR implements:
- `parallel_execution`: executes a given circuit for multiple input states.
- `parallel_reuploading_execution`: executes a given circuit for multiple parametrization values (reuploading)
both approaches are based on multi-processing and share the parallel_L-BFGS-B procedure.
This PR also:
- moves the parallel related code to `parallel.py`
- cleanup the `ParallelResources` singleton.
=> Parallel circuit evaluation

setup.py, src/qibo/hep/qpdf.py, src/qibo/models.py, src/qibo/optimizers.py
Few fixes to preserve the new code conventions.
=> small fixes

doc/source/examples.rst, src/qibo/abstractions/circuit.py, src/qibo/abstractions/gates.py, src/qibo/tests/test_circuits.py
Provides a text based circuit viewer, closes #145.
**Example:**
```python
from qibo.models import QFT
c = QFT(5)
print(c.draw())
```
@stavros11 @igres26 before polishing the code could you please let me know your opinion?
=> Circuit viewer

src/qibo/backends/numpy.py, src/qibo/backends/tensorflow.py, src/qibo/core/cgates.py, src/qibo/tests_new/conftest.py, src/qibo/tests_new/test_core_circuit_parametrized.py
This fixes the issue of importing custom operators when the non-custom tensorflow operators are used on a machine that cannot compile custom operators. Particularly I identified two issues:
1. Custom operators were indeed imported by some gates that  are only defined in `cgates.py` and not in `gates.py` (eg. the measurement gate). This was easy to fix because these gates do not actually use the custom operators.
2. The non-custom `initial_state` was not properly implemented when `is_matrix=True`.
=> Fix custom operator imports in tests

src/qibo/backends/__init__.py, src/qibo/backends/numpy.py, src/qibo/backends/tensorflow.py, src/qibo/core/cgates.py, src/qibo/tensorflow/custom_operators/__init__.py, src/qibo/tests_new/conftest.py, src/qibo/tests_new/test_abstract_circuit_qasm.py, src/qibo/tests_new/test_core_circuit_parametrized.py, src/qibo/tests_new/test_core_circuit_qasm.py, src/qibo/tests_new/test_core_gates.py
This PR:
- improves the mechanism to detect if custom operators are available
- if custom operators are not available but tf is available the defaulteinsum and matmuleinsum will be available.
- fixed tests_new to support `--engines numpy`
@stavros11 please have a look. I am still not able to run the `tests_new` with `--engine tensorflow` (when no custom operators are available) because circuits from some tests are still calling cgates (even if the backend is matmuleinsum and defaulteinsum).
=> Detach custom operators

.github/workflows/rules.yml, src/qibo/core/gates.py, src/qibo/parallel.py, src/qibo/tests/conftest.py, src/qibo/tests/test_callbacks.py, src/qibo/tests/test_density_matrix.py, src/qibo/tests/test_distributed.py, src/qibo/tests/test_evolution.py, src/qibo/tests/test_fusion.py, src/qibo/tests/test_hamiltonians.py, src/qibo/tests/test_measurements.py, src/qibo/tests/test_variational.py
Fixes the issue with the old `tests` mentioned in #316. This is mostly a temporary fix until we migrate all tests to `tests_new`.
Regarding the new tests, there may be a possibility to move the
```Python
original_backend = qibo.get_backend()
qibo.set_backend(backend)
...
qibo.set_backend(original_backend)
```
mechanism to `conftest.py` and avoid all the code repetition, however I am not yet sure if this could work.
=> Fix old tests for Windows

src/qibo/core/states.py, src/qibo/tests_new/test_core_states.py
Fixes #326 by modifying the einsum call used to trace-out density matrices to calculate the corresponding probability distribution for measurements.
=> Fix einsum in density matrix traceout

src/qibo/core/circuit.py, src/qibo/core/gates.py, src/qibo/tests/test_density_matrix.py, src/qibo/tests/test_qft.py, src/qibo/tests_new/test_core_circuit_features.py, src/qibo/tests_new/test_core_gates.py, src/qibo/tests_new/test_core_gates_density_matrix.py
Moves the state reshape required for non-custom backends inside the gates instead of the circuit. This fixes some compatibility issues between gates of different backends and makes testing easier. 
It also fixes #337 since the `tensor_shape` and `flat_shape` attributes are no longer required during circuit creation. For this point I also added a test that initializes a QFT for n=100 qubits and checks that the depth is 2n and the number of gates n^2/2 + n.
=> Move state reshape in gates

src/qibo/backends/tensorflow.py, src/qibo/config.py, src/qibo/tensorflow/custom_operators/cc/kernels/measurements.cc, src/qibo/tests_new/test_measurement_gate_probabilistic.py
As discussed, this PR removes the GPU ops and alleviates the computation by consuming more memory, but it is usually 2x faster than #332.
@stavros11 could you please have a look and then perform the benchmarks?
The last point is quite important in order to decide if we should keep the random categorical.
=> Speeding up Metropolis for frequency

src/qibo/core/cgates.py, src/qibo/tests_new/test_core_gates_density_matrix.py
This PR fixes a bug related to using controlled by Y gates with density matrices with the custom backend. To reproduce:
```Python
from qibo import models, gates
c = models.Circuit(2, density_matrix=True)
c.add(gates.Y(1).controlled_by(0))
state = c().state()
print(np.trace(state))
```
prints -1 while the trace of the density matrix should always be 1. This appears only in the custom backend, all other backends work fine.
=> Fix controlled by Y gates for custom backend

src/qibo/abstractions/states.py, src/qibo/core/hamiltonians.py, src/qibo/core/states.py, src/qibo/tests/test_hamiltonians.py, src/qibo/tests_new/test_core_states.py
=> Hamiltonian expectation for density matrices

src/qibo/backends/abstract.py, src/qibo/backends/numpy.py, src/qibo/core/gates.py, src/qibo/tests_new/test_backends_agreement.py
Fixes #342. In principle this is a tf issue as the existing code in master still works with numpy, I just changed the slicing to `K.gather` so that it works with Tensorflow too.
I think the problem of #342 should now be fixed but I would like to do a few more tests with more qubits because based on some other similar tf issues we fixed recently I suspect the tf einsum may fail in some cases. I am not 100% certain though.
=> Fix issue with tf slicing

src/qibo/backends/tensorflow.py, src/qibo/tests_new/test_tensorflow_custom_operators.py
As @igres26 pointed out, currently the seed used in the frequency custom operator is generated using the system's time during the backend initialization. Because the backend is normally initialized once when a script is executed, all calls of the `K.sample_frequencies` method return the same frequencies if executed in the same runtime. For example in:
```Python
probs = np.random.random(8)
probs = probs / np.sum(probs)
frequencies1 = K.sample_frequencies(probs, nshots=int(1e6))
frequencies2 = K.sample_frequencies(probs, nshots=int(1e6))
```
`frequencies1` will be exactly the same as `frequencies2`, while usually the user would expect them to be different. This is very relevant in notebooks where the same cell may be executed several times in the same runtime with the user expecting …
=> Use random seed for frequency custom operator

examples/shor/functions.py, examples/test_examples.py
Updates the semiclassical version of the Shor example to use the collapse and gate conditioned on measurement outcome functionality implemented in #352. The whole procedure can now implemented using a single circuit, without requiring to recreate a new one after each measurement.
Note that measured qubits are reset to |0> using an RX gate conditioned on the measurement outcome, like the following example:
```Python
results.append(c.add(gates.M(0, collapse=True)))
c.add(gates.RX(0, theta=np.pi * results[-1]))
```
We may substitute this by the `Reset` gate in the future, once we know how this is implemented experimentally.
=> Update semiclassical Shor example to use measurements with collapse

examples/shor/functions.py, examples/test_examples.py, src/qibo/abstractions/circuit.py, src/qibo/abstractions/gates.py, src/qibo/core/cgates.py, src/qibo/core/gates.py, src/qibo/core/measurements.py, src/qibo/tests_new/test_core_gates_features.py, src/qibo/tests_new/test_core_measurements.py, src/qibo/tests_new/test_measurement_gate_collapse.py
Implements the second question/point analyzed in #352 to allow performing multiple `collapse=True` shots using a single circuit call. The usage is the following:
```Python
c = Circuit(1)
c.add(gates.H(0))
output = c.add(gates.M(0, collapse=True))
result = c(nshots=100)
```
will perform 100 measurements by repeating the circuit execution. The samples are accessible via the `output` object, that is `output.samples()` will return a `(100, 1)` tensor. Note that execution with repetition is equivalent to:
```Python
samples = []
for _ in range(100):
c()
samples.append(output.samples())
```
It is also possible to use `output` to parametrize other gates:
```Python
c = Circuit(2)
c.add(gates.H(0))
output = c.add(gates.M(0, collapse=True))
c.add(gates.RX(1, theta=np.pi * output / 4))
result = …
```
=> Multiple collapse measurements with single circuit call

examples/aavqe/main.py, examples/adiabatic/optimize.py, examples/adiabatic3sat/main.py, examples/benchmarks/qaoa.py, examples/benchmarks/vqe.py, examples/qPDF/qPDF.ipynb, src/qibo/evolution.py, src/qibo/models.py, src/qibo/optimizers.py, src/qibo/tests/test_evolution.py, src/qibo/tests/test_variational.py
Closes #357. This PR propagates the extra flags from scipy to our optimizer and vqe/qaoa minimizer methods, and returns an extra object which holds the original result output from the underlying optimizer library.
=> Standarizing optimizers input and output

examples/variational_classifier/README.md, examples/variational_classifier/main.py
This PR fixes an error in the definition of the test set for the `variational classifier` example, described in #367 .
It also updates the README file accordingly to include the new test accuracy.
The arXiv reference for the variational classifier in the README file has also been modified.
=> Fix variational classifier

src/qibo/tensorflow/custom_operators/cc/kernels/apply_gate_kernels.cc, src/qibo/tensorflow/custom_operators/cc/kernels/transpose_state.cc
Based on the answer of [https://stackoverflow.com/questions/31465893/using-unsigned-long-long-as-iteration-range-in-for-loop-using-openmp](https://stackoverflow.com/questions/31465893/using-unsigned-long-long-as-iteration-range-in-for-loop-using-openmp), I think OpenMP doesn't like the `auto` option in parallelized for loops when this refers to an int64 integer.
Here I replace `auto` with `long` and this seems to fix the issue of not applying gates on CPU for more than 32 qubits.
=> Fix CPU custom operators for more than 32 qubits

src/qibo/backends/__init__.py, src/qibo/backends/abstract.py, src/qibo/backends/numpy.py, src/qibo/backends/tensorflow.py, src/qibo/core/states.py, src/qibo/tests/conftest.py, src/qibo/tests/test_variational.py, src/qibo/tests_new/test_backends_agreement.py, src/qibo/tests_new/test_backends_init.py, src/qibo/tests_new/test_core_circuit_backpropagation.py, src/qibo/tests_new/test_measurement_gate_collapse.py, src/qibo/tests_new/test_measurement_gate_probabilistic.py
Simplifies the backend switching mechanism by creating a seperate backend class for each of the einsum backends. For example currently we have a single `NumpyBackend` class that handles both `numpy_defaulteinsum` and `numpy_matmuleinsum`. In this PR I seperate the backends by create different classes `NumpyDefaultEinsumBackend` and  `NumpyMatmulEinsumBackend`. I believe this allows a cleaner switching function and may be easier to maintain if we add more backends either for simulation or hardware.
There is no change from the user perspective, that is the user can still switch the backends using `qibo.set_backend("custom")`, `qibo.set_backend("defaulteinsum")`, `qibo.set_backend("numpy_defaulteinsum")`, etc..
=> Simplify backend switch

src/qibo/optimizers.py
Closes #381. @DiegoGM91 could you please confirm this solves the ambiguity?
=> renaming cma function

src/qibo/core/gates.py, src/qibo/tests_new/test_tensorflow_custom_operators.py
Closes #386. I don't think there is some simple way to catch prints from pytest but let me know.
=> removing undesired prints

src/qibo/tests_new/test_prints.py
Following what was discussed in #387, this adds a test that checks that our code does not contain any undesired `print` statements.
=> Test that code does not contain `print` statements

src/qibo/backends/abstract.py, src/qibo/backends/matrices.py, src/qibo/backends/numpy.py, src/qibo/backends/tensorflow.py, src/qibo/core/hamiltonians.py, src/qibo/tests_new/conftest.py, src/qibo/tests_new/test_backends_init.py, src/qibo/tests_new/test_backends_matrices.py
Simplifies the mechanism that creates `qibo.matrices` so that we don't need a separate matrix class for each backend. Hopefully fixes the issue described in #400.
@scarrazza I opened this PR with master as base because this simplification is independent of qibo_sim but if you prefer I can rebase it for `simtfrename` in order to merge there and check if the pylint issue is fixed.
=> Make matrices backend agnostic

setup.py, src/qibo/backends/__init__.py
Implements a simple version check for backends, including the mirroring with setup.py.
=> adding version checks for backends

.github/workflows/rules.yml, .github/workflows/wheels.yml, doc/source/installation.rst, src/qibo/parallel.py, src/qibo/tests/test_backends_init.py, src/qibo/tests/test_models_variational.py, src/qibo/tests/test_parallel.py
Fixes #415. It seems that the issue comes from a `set_device` test that does not reset the device properly back to GPU when it runs for the numpy backend. All tests now work both on CPU and GPU for me. @scarrazza please confirm that it is okay for you too.
=> Fix `set_device` test for GPU

.github/workflows/rules.yml, .github/workflows/wheels.yml, doc/source/installation.rst, src/qibo/models/grover.py, src/qibo/parallel.py, src/qibo/tests/test_models_grover.py, src/qibo/tests/test_models_variational.py, src/qibo/tests/test_parallel.py
Changed the Grover model where the iterative model always outputs something even if it runs for too long of a time.
=> Small Grover change

src/qibo/backends/__init__.py
The latest master after merging the hardware backend switcher gives a warning that Tensorflow is not installed even if it is installed. For example the following script
```Python
import qibo
print(qibo.get_backend)
```
prints
```
[Qibo|WARNING|2021-06-02 13:22:24]: Tensorflow is not installed, falling back to numpy. Numpy backend uses `np.einsum` and supports CPU only. To enable GPU acceleration please install Tensorflow with `pip install tensorflow`. To install the optimized Qibo custom operators please use `pip install qibotf` after installing Tensorflow.
qibotf
```
so the warning appears even though the default backend is properly set to `qibotf`. @scarrazza could you please confirm that you also get this warning?
This PR should fix this issue.
=> Tensorflow not installed warning

doc/source/advancedexamples.rst, doc/source/qibo.rst, examples/adiabatic3sat/main.py, src/qibo/__init__.py, src/qibo/abstractions/abstract_gates.py, src/qibo/abstractions/hamiltonians.py, src/qibo/backends/abstract.py, src/qibo/backends/numpy.py, src/qibo/backends/tensorflow.py, src/qibo/core/gates.py, src/qibo/core/hamiltonians.py, src/qibo/core/states.py, src/qibo/hamiltonians.py, src/qibo/models/evolution.py, src/qibo/models/variational.py, src/qibo/solvers.py, src/qibo/symbols.py, src/qibo/tests/test_core_hamiltonians_from_symbols.py, src/qibo/tests/test_core_hamiltonians_symbolic.py
Following the discussion in #413 this calculates the `hamiltonian.expectation` term-by-term instead of constructing the full matrix. The custom backend can also be used for this calculation even for Hamiltonians with terms acting on more than two qubits because the calculation involves only single qubit gates. 
Here are some benchmarks using a Fermi-Hubbard Hamiltonian provided by @igres26:
nsites | nqubits | qibotf (this branch) | tensorflow (master) | numpy (master)
-- | -- | -- | -- | --
3 | 9 | 0.043816 | 0.053682 | 0.008743
4 | 12 | 0.061650 | 0.094803 | 0.030591
5 | 15 | 0.117778 | 0.200112 | 0.208575
6 | 18 | 0.280394 | 0.840739 | 2.054210
7 | 21 | 3.864714 | 9.843416 | 21.948270
8 | 24 | 29.415665 | 90.591800 | 232.787657
The way this is implemented currently is the following:
* …
=> Hamiltonian expectation using terms

doc/source/examples.rst, src/qibo/__init__.py, src/qibo/backends/tensorflow.py, src/qibo/config.py, src/qibo/tests/test_backends_init.py
Following a discussion with @igres26, this implements a getter/setter for the threshold value beyond which measuring shot frequencies will fall to the Metropolis custom operator.
The reason we need this is that the current Metropolis implementation does not seem to work very well for specific (usually sparse) distributions. Of course the proper solution would be to improve the custom operator itself, however the threshold setter is a good temporary solution that allows the user to disable the custom operator if its results are not good, by setting a very high threshold (eg. 10^12). The default tensorflow/numpy implementation is quite fast for up to 10^7 shots anyway, which is sufficient for many applications.
=> Set threshold for using Metropolis custom op

src/qibo/__init__.py, src/qibo/backends/__init__.py, src/qibo/backends/abstract.py, src/qibo/backends/numpy.py, src/qibo/backends/tensorflow.py, src/qibo/config.py, src/qibo/core/distcircuit.py, src/qibo/core/distutils.py, src/qibo/core/states.py, src/qibo/parallel.py
As we discussed, this moves the `set_threads` and `get_threads` methods at the backend level so that we can set the number of threads for numba properly. I checked and it seems to work properly for qibojit, for example
```Python
import qibo
from qibo.models import QFT
qibo.set_backend("qibojit")
qibo.set_threads(10)
c = QFT(28)
state = c()
```
should use 10 threads. The default number of threads is read from `psutil` (unless the `OMP_NUM_THREADS` variable is provided) and is equal to the physical number of cores. This is usually half of total threads.
Note that the above mechanism works for qibotf, but not for pure tensorflow operators. So when using the pure `tensorflow` backend, `set_threads` is completely ignored and when using `qibotf`, custom operators will use the proper number of …
=> Set number of threads for qibojit

.github/workflows/rules.yml, examples/EF_QAE/main.py, examples/aavqe/main.py, examples/adiabatic3sat/functions.py, examples/adiabatic3sat/main.py, examples/autoencoder/main.py, examples/benchmarks/main.py, examples/benchmarks/qaoa.py, examples/benchmarks/vqe.py, examples/falqon/README.md, examples/qsvd/main.py, examples/qsvd/qsvd.py, examples/reuploading_classifier/main.py, examples/reuploading_classifier/qlassifier.py, examples/test_examples.py, examples/variational_classifier/qclassifier.py, src/qibo/backends/__init__.py, src/qibo/backends/numpy.py, src/qibo/parallel.py, src/qibo/tests/test_core_callbacks.py, src/qibo/tests/test_models_variational.py, src/qibo/tests/test_parallel.py
With qibojit installed the multiprocessing import cannot be changed to "fork" mode on macos. This PR disables the parallel feature for macos. I believe we should schedule a revision of this module in the future, in particular considering better parallel algorithms rather than forcing circuit copies and async evaluation. @stavros11 please let me know your opinion.
=> disabling parallel evaluation on darwin

src/qibo/backends/__init__.py, src/qibo/backends/numpy.py, src/qibo/backends/tensorflow.py, src/qibo/tests/test_backends_init.py
Fixes #442 by:
* Modifying `qibo.set_threads` to update the number threads only for the currently active backend.
* Raising warnings when using `qibo.set_threads` with the numpy or tensorflow backends which do not support this kind of thread setting.
=> Set threads warnings

src/qibo/abstractions/abstract_gates.py, src/qibo/backends/numpy.py, src/qibo/backends/tensorflow.py, src/qibo/core/gates.py, src/qibo/tests/test_core_gates_features.py
Fixes #444 by making the `.matrix` property to return the matrix representation of gates in the computational basis. @igres26 you can try now for the U1 and you should get the correct matrix with both `.matrix` and `.unitary`.
The backends now use different matrix properties which should not be used by the user. These are `native_op_matrix` for numpy/tensorflow backends and `custom_op_matrix` for qibojit/qibotf backends.
=> Fix gate.matrix property

src/qibo/core/callbacks.py, src/qibo/tests/test_core_callbacks.py
This PR raises an error if the user allocates multiple circuits using different number of qubits but sharing the same `EntanglementEntropy` object. @igres26 could you please check if this PR raises a proper error in your example?
=> EntanglementEntropy use circuits with fixed nqubits

doc/source/qibo.rst, src/qibo/abstractions/abstract_gates.py, src/qibo/abstractions/callbacks.py, src/qibo/abstractions/circuit.py, src/qibo/backends/abstract.py, src/qibo/backends/numpy.py, src/qibo/backends/tensorflow.py, src/qibo/core/callbacks.py, src/qibo/core/circuit.py, src/qibo/core/distcircuit.py, src/qibo/core/distutils.py, src/qibo/core/fusion.py, src/qibo/core/gates.py, src/qibo/core/states.py, src/qibo/core/terms.py, src/qibo/tests/test_abstract_callbacks.py, src/qibo/tests/test_abstract_gates.py, src/qibo/tests/test_core_fusion.py, src/qibo/tests/test_core_gates.py, src/qibo/tests/test_core_gates_controlled.py, src/qibo/tests/test_core_gates_density_matrix.py, src/qibo/tests/test_core_gates_features.py, src/qibo/tests/test_measurement_gate.py, src/qibo/tests/test_models_evolution.py
Following #446 here we remove `.unitary` in favour of `.matrix`.
=> replacing unitary with matrix

examples/reuploading_classifier/qlassifier.py, src/qibo/backends/abstract.py, src/qibo/backends/hardware.py, src/qibo/backends/jit.py, src/qibo/backends/tensorflow.py, src/qibo/core/distcircuit.py, src/qibo/models/circuit.py, src/qibo/optimizers.py, src/qibo/tests/conftest.py, src/qibo/tests/test_cirq.py, src/qibo/tests/test_core_circuit.py, src/qibo/tests/test_core_circuit_backpropagation.py, src/qibo/tests/test_models_circuit.py, src/qibo/tests/test_models_evolution.py
Minor changes to avoid hardcoding backend names.
We should complete the docs about the implementation of a new backend.
In principle we could remove the .compile method, however the mechanism might be useful for hardware optimization so I am keeping this feature.
@stavros11 please let me know if you see some extra generalization that makes sense at this point. Here I decided to keep the profiles.yml as light as possible, given that we are already exposing the backend class inheritance, so we can use that directly instead of reading and setting from the profile.
=> using abstract backend attributes

src/qibo/abstractions/circuit.py
Closes #462. I added some edits that came to my mind while reading `abstractions/circuit.py`, let me know if they are ok or if I should undo them.
=> Remove unused flag from AbstractCircuit class

doc/source/contributing.rst, src/qibo/parallel.py, src/qibo/tests/test_prints.py
If I understand correctly, the code in ``src/qibo/tests/test_prints.py`` implements a test that checks if the source code contains `print` statement. If this is so, such test is not working properly. In fact, the `print` statement occurs twice:
https://github.com/qiboteam/qibo/blob/28171d29c8654748d2b436338f1fa99de8ae7f92/src/qibo/parallel.py#L56-L57
but no error is raised.
I found two issues in the CodeText class:
- If the code starts with `"""`,  then the first piece will be an empty string, the second will be the content of a docstring, the third will be code, and so on.
https://github.com/qiboteam/qibo/blob/28171d29c8654748d2b436338f1fa99de8ae7f92/src/qibo/tests/test_prints.py#L28
On the other hand, if the code doesn't start with `"""`, the first piece will contain proper code, the …
=> Fix tests about `print` statements

.github/workflows/rules.yml, src/qibo/abstractions/abstract_gates.py, src/qibo/abstractions/circuit.py, src/qibo/abstractions/gates.py, src/qibo/tests/test_abstract_gates.py
Closes #472. I renamed ``Gate.on_qubits()`` to ``Gate._on_qubits()`` in
- ``qibo.abstractions.abstract_gates.Gate`` (+ some comments)
-  ``qibo.abstractions.abstract_gates.SpecialGate``
-  ``qibo.abstractions.abstract_gates.Channel``
- ``qibo.abstractions.gates.Unitary``
- ``qibo.abstractions.circuit.AbstractCircuit.on_qubits()``
and I also modified the tests accordingly. I also made some minor fixes in the docstrings.
I should have found all occurences of such method. I'll ask for review as soon as I solve the problem with pylint.
=> Rename ``Gate.on_qubits()`` to ``Gate._on_qubits()``

doc/source/advancedexamples.rst, src/qibo/core/hamiltonians.py, src/qibo/core/terms.py, src/qibo/hamiltonians.py, src/qibo/symbols.py, src/qibo/tests/test_core_hamiltonians_from_symbols.py, src/qibo/tests/test_core_hamiltonians_symbolic.py, src/qibo/tests/test_core_hamiltonians_trotter.py, src/qibo/tests/test_core_terms.py, src/qibo/tests/test_hamiltonians.py
Fixes #469. As discussed in the issue, the main bottleneck comes from the `sympy.expand` call that is used on the given sympy expression of the Hamiltonian form when a `SymbolicHamiltonian` is constructed. This call is useful when parsing the symbolic terms to [Qibo terms](https://github.com/qiboteam/qibo/blob/sympyexpand/src/qibo/core/terms.py). Given that the Qibo term representation of Hamiltonian is only useful when trotterizing, here I disable this calculation unless it is required (eg. when the user asks for trotterization). The idea is that Hamiltonians that cause #469 are non-local and therefore trotterization won't be useful for them anyway, so it will be unlikely that the user will get this performance issue.
The second part implemented here is a function that calulates the full …
=> Remove sympy.expand call when constructing SymbolicHamiltonian

src/qibo/abstractions/callbacks.py, src/qibo/abstractions/gates.py, src/qibo/models/evolution.py, src/qibo/models/grover.py, src/qibo/models/variational.py
In this PR I fixed some broken examples in the docstrings. I haven't made an exhaustive search so some examples may still be broken.
Let me know if it is all ok, in particular with the ``VariationalLayer`` (I had to change a lot to fix it)
=> Fix some examples in docstrings

src/qibo/tests/test_core_callbacks.py, src/qibo/tests/test_core_hamiltonians.py
In this PR and in https://github.com/qiboteam/qibojit/pull/36 I am trying to fix issue https://github.com/qiboteam/qibojit/issues/34 concerning tests with AMD GPUs.
In particular, there are two tests in Qibo with calls to ``np.linalg.eigh`` and ``np.linalg.eigvalsh``.
When these calls are performed with a CuPy object as argument, it seems that somehow there is a automatic call to ``cp.linalg.eigh`` or ``cp.linalg.eigvalsh`` (I think that this behavior is very confusing).
The problem is that this behavior bypasses the fallback mechanism implemented in https://github.com/qiboteam/qibojit/pull/36 and a ``rocblas_not_implemented_status`` error is raised.
The easiest fix is to replace the hard-coded call to NumPy with the backend ``K`` in these tests.
However, I wonder if there was a specific …
=> Remove some hard-coded ``np.linalg`` calls from tests

.github/workflows/deploy.yml, .github/workflows/rules.yml, doc/source/getting-started/installation.rst, doc/source/getting-started/quickstart.rst, setup.py
Here we remove python3.6 support and simplify some installation targets.
=> disabling py36

.github/workflows/deploy.yml, .github/workflows/rules.yml
In #475 a trigger on pull requests was added to the workflows.
I think we should remove it otherwise the CI runs twice for each push to a branch with an open PR.
=> Fix CI running twice

src/qibo/core/measurements.py, src/qibo/core/states.py
Linked to PR https://github.com/qiboteam/qibojit/pull/48 .
When using CuPy, the fallback to CPU doesn't work well because we change device but we don't cast the arrays to Numpy. A added a cast operation in ``core.states.VectorState.probabilities()`` to fix https://github.com/qiboteam/qibojit/issues/46, but I also needed to implement the fallback for the computation of frequencies, which has the same memory issue.
This PR is still work in progress, as I need to understand if everything works fine.
https://github.com/qiboteam/qibojit/blob/74733be84dcaa8753863df2efa1773ad6cf27110/src/qibojit/custom_operators/__init__.py#L197-L211
In ``JITCustomBackend`` we already have an automatic fallback to Numba + casting operation (see the link above), but there's an execution branch in which we call …
=> Fix CPU fallback

src/qibo/abstractions/states.py, src/qibo/core/states.py, src/qibo/tests/test_core_states.py
Closes #519. We provide the following options:
```Python
c = models.Circuit(5)
c.add(gates.H(1))
result = c()
print(result) # (0.70711+0j)|00000> + (0.70711+0j)|01000>
print(result.state(symbolic=True)) # (0.70711+0j)|00000> + (0.70711+0j)|01000>
print(result.symbolic(decimals=1)) # (0.7+0j)|00000> + (0.7+0j)|01000> 
print(result.symbolic(decimals=2)) # (0.71+0j)|00000> + (0.71+0j)|01000>
```
The `decimals` argument controls the number of decimals and the default is 5. Zero amplitudes are ignored.
@scarrazza, @igres26 let me know if you agree. I will implement something similar for density matrices.
=> State in computational basis

src/qibo/backends/numpy.py, src/qibo/core/states.py
Closes #517. In this PR I fixed issue #517 by casting the state vector to double precision before computing the probabilities.
The memory overhead w.r.t. main should be around 33%.
In the meantime, I made a small change in the NumPy cast, to ensure that no arrays are duplicated if not needed. Let me know your opinion.
=> Fix probabilities do not sum to 1

src/qibo/backends/abstract.py, src/qibo/core/measurements.py
I moved the CPU fallback from ``qibo.core.measurements.frequencies`` to ``qibo.core.measurements._calculate_frequencies``, so that we call it with arguments and the CPU fallback implemented in PR https://github.com/qiboteam/qibojit/pull/54 converts them, if needed.
=> Move CPU fallback for frequencies

src/qibo/tests/test_backends_agreement.py
This PR contains a minor fix on the qibo tests in order to support a new backend for `qibojit` on GPU based on the NVIDIA [CuQuantum](https://github.com/NVIDIA/cuQuantum) library which is currently under-development in PR qiboteam/qibojit#57.
=> Fix qibo tests to support CuQuantum Backend

src/qibo/tests/test_prints.py
As mentioned in qiboteam/qibojit#57 `test_prints.py` fails when executed in environment with cuquantum installed and a GPU enabled. For me this happens for both Python 3.8 and 3.9 and only after installing cuqantum, even if I use the master/main branches of qibo and qibojit. This implements a simple fix.
@andrea-pasquale, let me know if it works for you.
=> Fix `test_prints.py` when cuquantum is installed

doc/source/getting-started/installation.rst
This PR is related to the cuQuantum backend from qiboteam/qibojit#57.
I've updated the installation instructions and I've added cuQuantum along the other platforms available in qibojit.
Let me know what you think.
=> Installation instructions for cuQuantum backend

examples/benchmarks/main.py, src/qibo/tests/test_backends_agreement.py
In some tests the old ``engine`` member of ``JitCustomBackend`` was still used. I renamed it to ``platform``.
=> Fix engine not renamed to platform in some tests

src/qibo/abstractions/circuit.py
Fixes the issue discovered by @AdrianPerezSalinas [here](https://github.com/qiboteam/qibo/pull/525#issuecomment-1017262595).
=> Add S and T gates to `circuit.draw()`

src/qibo/models/circuit.py, src/qibo/tests/test_models_circuit.py
Removes some coverage exceptions for #543. @andrea-pasquale, the issue was that these tests were only testing for the default backend (qibojit numba) for which the multigpu is now disabled. I enabled them for all available backends so that the multigpu code is tested virtually from qibotf. Let me know if you agree.
Btw, if at some point we disable/remove qibotf from the test we will have several coverage issues with the distributed circuit.
=> Remove some coverage exceptions

doc/source/code-examples/advancedexamples.rst, src/qibo/backends/numpy.py, src/qibo/core/distcircuit.py, src/qibo/models/circuit.py, src/qibo/models/qgan.py, src/qibo/tests/test_models_circuit.py, src/qibo/tests/test_models_qgan.py
In this PR I fixed the error message for the distributed circuit according to the renaming of the backends implemented in #533. The error shown now in the case of cuquantum is the following
```
NotImplementedError: Distributed circuit is not supported by the qibojit (cuquantum) backend.
```
The same mechanism is applied when using the numba backend.
=> Fix message error in distributed circuit

doc/source/api-reference/qibo.rst, src/qibo/abstractions/states.py, src/qibo/core/states.py, src/qibo/tests/test_abstract_states.py, src/qibo/tests/test_core_states.py, src/qibo/tests/test_core_states_distributed.py
Following #545, this implements the option to create a deep copy of a state using `VectorState.copy(deep=True)`. I also added in the docs (States section) that qibojit and qibotf perform in-place updates so the state (and all its shallow copies) will be modified if it is used as initial state in a circuit or time evolution.
=> Implement state deep copy

setup.py, src/qibo/abstractions/circuit.py, src/qibo/tests/test_abstract_circuit.py
This PR fixes #546. The current version of qibo does not allow to draw circuits where there are channel gates.
I've added a few labels to identify these channels. In order to differentiate those from the usuale gates I've added a `c` at the end. For example in the case of the `PauliNoiseChannel` the output should be the following:
```python
from qibo import models, gates
c = models.Circuit(2, density_matrix=True)
c.add(gates.X(1))
c.add(gates.PauliNoiseChannel(0, px=0.3))
result = c()
print(c.draw())
```
The same mechanism using different labels is applied for all the other channels.
We can also change the name of the labels that I've chosen.
Let me know what you think.
=> Adding channels to circuit.draw()

src/qibo/symbols.py, src/qibo/tests/test_core_hamiltonians_from_symbols.py
This adds an identity to `qibo.symbols` to simplify the construction of Hamiltonians for some cases, such as the one we were discussing starting from #556.
=> Add identity symbol

src/qibo/abstractions/callbacks.py, src/qibo/core/callbacks.py, src/qibo/tests/test_core_callbacks.py
Implements a callback that keeps track of the full state vector or density matrix during circuit simulation. This was requested by @igres26 in #555. Usage is similar to existing callbacks, one can add this to a circuit, in the place which a stamp of the state is required, using a `CallbackGate`.
This PR is complete, I just mark it as do not merge because the test will change if we merge qiboteam/qibojit#74.
=> Full state callback

src/qibo/abstractions/circuit.py, src/qibo/tests/test_abstract_circuit.py, src/qibo/tests/test_core_circuit_noise.py
Closes #563.
As already discussed in today's meeting, the problem was related to the `add` method of `AbstractCircuit`.
When the new circuit is created the `repeated_execution` attribute, which allows to re-execute the circuit for every
shot, was set by default to `False`. This is why when adding the noisy circuit with its inverse the sampling was odd.
Now `repeated_execution` is set to:
```python
newcircuit.repeated_execution = old_circuit.repeated_execution or circuit_to_add.repeated_execution
```
Therefore if one of the two circuits requires to re-execute the circuit the new circuit will also be re-executed for every shot. 
I've also added tests about this.
Let me know what you think @igres26 @scarrazza @stavros11.
=> Fix sampling when using `circuit.add()`

src/qibo/models/variational.py, src/qibo/tests/test_models_variational.py
Temporary fix for #558 until we make the model more flexible to allow applying operators of different sizes.
=> Raise error if QAOA Hamiltonians have different nqubits

src/qibo/abstractions/gates.py, src/qibo/backends/abstract.py, src/qibo/config.py, src/qibo/core/gates.py, src/qibo/tests/test_abstract_gates.py, src/qibo/tests/test_backends_init.py, src/qibo/tests/test_core_gates.py
Fixes #562 by using a tolerance when checking the probability sum. Now the error is raised when
```Python
sum(p) > 1 + K.precision_tol
```
instead of 
```Python
sum(p) > 1
```
where `K.precision_tol` is defined in config.py for single and double precision.
=> Relax probability sum check in `UnitaryChannel`

doc/source/api-reference/qibo.rst, src/qibo/abstractions/abstract_gates.py, src/qibo/abstractions/circuit.py, src/qibo/abstractions/gates.py, src/qibo/core/circuit.py, src/qibo/core/gates.py, src/qibo/tests/test_abstract_gates.py, src/qibo/tests/test_core_fusion.py, src/qibo/tests/test_core_gates.py
Extends the `circuit.fuse()` to work with more than two qubits in the fused gates. The maximum number of qubits in a `FusedGate` is passed as argument in `circuit.fuse(max_qubits)`.
Here are some benchmarks comparing this with the two qubit fusion currently implemented in qibo:
<details>
<summary>variational - cupy</summary>
|   nqubits |   no fusion |  fusion master |  fusion (max_qubits=2) this branch |
|----------:|------------------------:|-------------------------------:|--------------------------------:|
|        20 |              0.00650024 |                     0.00381665 |                      0.00400567 |
|        21 |              0.013676   |                     0.00941253 |                      0.00939865 |
|        22 |              0.0244068  |                     0.0174996 …
=> Multi-qubit fusion

setup.py, src/qibo/backends/__init__.py, src/qibo/tests/test_backends_init.py
Attempting to dump the backend object `K` with `dill` leads to a maximum recursion error which is associated with the `__getattr__` method that we use for implementing the backend methods. Btw, method seems a bit unstable in general, it could be useful to consider alternatives.
This PR implements a workaround for dill by defining custom `__setstate__` and `__getstate__` methods for the backend.
=> Fix pickle for the backend object

src/qibo/backends/__init__.py, src/qibo/tests/test_backends_init.py
The following:
```py
import qibo
import dill
qibo.set_backend("qibolab")
dill.dump_session("session.pkl")
dill.load_session("session.pkl")
qibo.set_backend("numpy")
```
namely changing the backend after loading a session from pickle fails with `AttributeError`. Here the `__getitem__` and `__setitem__` methods are update to pickle and load all the attributes of the `Backend` object to fix this issue.
=> Fix backend pickle

.github/workflows/rules.yml
Includes cupy in actions. @stavros11 thanks for pointing this out.
=> testing distributed circuits with cupy

.github/workflows/rules.yml
I pinned the version of markdown to 3.3.7 to fix the issue with the compilation of documentation. @scarrazza, I am not sure if that's the best solution but it works for now.
=> Fix docs compilation

src/qibo/backends/abstract.py, src/qibo/backends/numpy.py, src/qibo/hamiltonians/hamiltonians.py
Fix #639.
@chmwzc if you have time please give a try if this solves your issue.
The following script can be used to compare with master
```py
import numpy as np
from qibo.hamiltonians import XXZ
nqubits = 20
state = np.random.random(2 ** nqubits) + 1j * np.random.random(2 ** nqubits)
state = state / np.sqrt(np.sum(np.abs(state) ** 2))
ham = XXZ(nqubits, dense=False)
expectation = np.real(np.dot(np.conj(state), ham @ state))
print(expectation)
print(ham.expectation(state))
```
=> Fix expectation value of symbolic Hamiltonian

src/qibo/gates/abstract.py, src/qibo/gates/gates.py, src/qibo/tests/test_models_circuit_parametrized.py
=> Fix `on_qubits` with `set_parameters`

.github/workflows/rules.yml, src/qibo/backends/__init__.py, src/qibo/backends/npmatrices.py, src/qibo/backends/numpy.py, src/qibo/backends/tensorflow.py, src/qibo/tests/test_parallel.py
Fixes #673. There is a name collision because `matrices` is the name of a module under backends but also defined in the `__init__.py` (see #674 for details). Here I rename matrices.py to npmatrices.py to fix this.
Qibojit only works using qiboteam/qibojit#92.
Checklist:
=> Rename matrices.py to npmatrices.py

doc/source/appendix/citing-qibo.rst
=> Added ichep2022 proceedings to references in doc

src/qibo/hamiltonians/abstract.py, src/qibo/hamiltonians/hamiltonians.py, src/qibo/states.py, src/qibo/tests/test_hamiltonians.py, src/qibo/tests/test_hamiltonians_symbolic.py, src/qibo/tests/test_states.py
In this PR I implemented the computation of expectation values of `Zs` operators from counts. The input is the frequencies `result.frequencies(binary=True)` and a mapping for the qubits indices. For example, suppose we have a 10 qubit circuit but we are measuring 5 of them `[1,3,5,7,9]` and we want to compute an observable that acts on those or less qubits `Z(5)*Z(3)*Z(9)`. Then, `qubit_map=[1,3,5,7,9]`.
Checklist:
=> Expectation values from samples

setup.py
In order to compile `sphinx` with the new theme, `furo` must be installed. I modified the `setup.py` file by adding it in the `extras_require` where we currently have `sphinx_rtd_theme`.
=> Added furo as extras_require in setup.py

doc/source/conf.py, src/qibo/__init__.py
As discussed in #691, here we remove the `qibo` logo from the `conf.py` file which is used while compiling the documentation.
=> rm qibo logo from conf.py

doc/source/api-reference/qibo.rst, src/qibo/backends/npmatrices.py, src/qibo/gates/gates.py, src/qibo/models/circuit.py, src/qibo/tests/test_gates_gates.py
=> add iswap gate

doc/source/appendix/citing-qibo.rst
This is a very tiny PR, I saw a typo into the `qibojit` reference.
Perhaps this branch can be kept open to correct any errors like this that we find.
=> fixing typo in docs appendix

src/qibo/gates/abstract.py, src/qibo/gates/gates.py, src/qibo/tests/test_gates_abstract.py
When changing the parameters of a parametrized gate the `gate.init_kwargs` dictionary is not updated. Therefore if a new gate is created after it will have the old parameter values. For example
```py
gate = gates.RX(0, theta=0)
gate.parameters = 0.5
gate2 = gates.__class__(*gate.init_args, **gate.init_kwargs)
```
This is relevant among other things for the [transpiler](https://github.com/qiboteam/qibolab/blob/d64cc98afbdc23adc1e472d70d8c1827d5f8da96/src/qibolab/transpilers/connectivity.py#L100), which is using this when creating new gates that respect hardware connectivity.
Checklist:
=> Update `gate.init_kwargs` when setting new parameters

doc/source/conf.py
With this PR the documentation's font is changed into "Ubuntu", which is the one used in the webpage.
=> Ubuntu font in the documentation

doc/source/conf.py, doc/source/index.rst
In this PR the software's release is added to the doc's side-bar (in the front-page) and removed from the introductory text. 
In order to show e.g.: `Release 0.1.10dev0`, I set "Release" where the package name should be placed. I know it is conceptually wrong, but it seemed the best solution to avoid repetition (Qibo is already mentioned in the navbar) and to clarify that the string `0.1.10dev0` refers to the release.
If there is a more elegant way, it is certainly preferable.
=> Moved "qibo release" to the doc's side-bar

src/qibo/gates/channels.py, src/qibo/tests/test_gates_channels.py
This PR fixes a bug in the thermal relaxation channel when $T_2>T_1$. In this case, the implementation of the channel uses a Choi-matrix representation.  There is a small error in the definition of this matrix. This implies that applying the channel on a density matrix gives a final state $\rho_f$ with $\operatorname{tr}(\rho_f)\neq1$.
```python
import numpy as np
from qibo.backends import construct_backend
from qibo.tests.utils import random_density_matrix
backend=construct_backend("numpy")
t1 = 0.5
t2 = 0.7
time = 0.4
excpop = 0
initial_rho = random_density_matrix(3)
gate = gates.ThermalRelaxationChannel(
0, t1, t2, time=time, excited_population=excpop
)
final_rho = gate.apply_density_matrix(backend, np.copy(initial_rho), 3)
print(final_rho.trace())
```
Checklist:
=> Thermal relaxation channel

doc/source/conf.py
After a discussion I had with the @qiboteam/coredevs, I propose to return to the original Furo font for the time being. 
Right now it is important to have a stable and presentable version of the documentation by the release (in a few days). We propose to address the restoration of the style in more detail at a later date.
If you agree with this, I propagate this choice in `qibolab` and `qibocal` too.
=> rm Ubuntu font from furo configuration

doc/source/api-reference/qibo.rst, src/qibo/quantum_info/basis.py, src/qibo/tests/test_quantum_info_basis.py
=> unvectorization function

src/qibo/gates/channels.py, src/qibo/tests/test_gates_channels.py
This PR implements a fix for issue #718. Debugging the code, I found that the bottleneck was in
https://github.com/qiboteam/qibojit/blob/df5f2360bf89dace3bf6833cde7f0d68999da94f/src/qibojit/backends/cpu.py#L182
The depolarizing channel is given by 
$\mathcal{E}(\rho)=(1-\lambda)\rho+\frac{\lambda}{2^n}I=(1-\frac{(4^n-1)\lambda}{4^n})\rho+\frac{\lambda}{4^n}{\sum}_{j=2}^{4^n}P_j\rho P_j^t$
where $P_j$ denotes all products of $n$ Pauli matrices and the identity $(P_1=I^{\otimes n})$.
The channel is currently implemented as a sum of Kraus operators which allows it to be used with state vectors and density matrices. However, when running density matrix circuits with qibojit this implementation turns out to be too slow.
So I have implemented the channel as …
=> Depolarizing channel

examples/adiabatic/linear.py, examples/adiabatic/optimize.py, examples/adiabatic/trotter_error.py, examples/test_examples.py
I was trying to use the code in https://github.com/qiboteam/qibo/tree/master/examples/adiabatic and wasn't working due to the usage of `.numpy()` and how the callbacks were being called. I guess this went unnoticed because it is missing from the [examples](https://github.com/qiboteam/qibo/blob/master/examples/test_examples.py)
I made some minimal changes so that it works for me but let me know if I'm using the correct functions/options (for instance, the `callback.apply` looks a bit cumbersome to me, but reading the code seemed like the right one for the use case).
Checklist:
=> Fix to adiabatic example

src/qibo/gates/channels.py
I updated CUDA and cupy on my machine and I realised that the depolarizing channel raises a `TypeError` when applying it to density matrix circuits and running them on gpu with `qibojit-cupy` using the latest version of `cupy` (`cupy-cuda12x`). This PR fixes it.
Checklist:
=> Depolarizing channel on gpu

src/qibo/backends/numpy.py, src/qibo/hamiltonians/adiabatic.py, src/qibo/hamiltonians/hamiltonians.py, src/qibo/models/circuit.py, src/qibo/models/error_mitigation.py
This PR solves #776. 
To solve the following error, I have disabled the `pylint` error locally, because the code looks good to me.
@AlejandroSopena confirms that the code works as expexted.
```
************* Module qibo.hamiltonians.hamiltonians
src/qibo/hamiltonians/hamiltonians.py:566:26: E1101: Instance of 'HamiltonianTerm' has no 'factors' member (no-member)
src/qibo/hamiltonians/hamiltonians.py:571:19: E1101: Instance of 'HamiltonianTerm' has no 'factors' member (no-member)
src/qibo/hamiltonians/hamiltonians.py:571:44: E1101: Instance of 'HamiltonianTerm' has no 'factors' member (no-member)
```
Checklist:
=> fix pylint errors

src/qibo/hamiltonians/models.py, src/qibo/tests/test_hamiltonians_models.py, src/qibo/tests/test_noise.py
Closes #774 and fixes pylint and failing tests for noise model (after #672 merge).
Checklist:
=> Fix hamiltonian models neighbour and noise model tests/lint

src/qibo/tests/test_quantum_info_superoperator_transformations.py
=> Fix `test_choi_to_kraus()` randomly crashing

src/qibo/gates/channels.py
This PR replaces $\text{Tr}\rho$ with $\text{Tr}_q[\rho]$ in the documentation of `DepolarizingChannel`, `ResetChannel` and `ThermalRelaxationChannel`.
Checklist:
=> Changed documentation of channels.

src/qibo/backends/numpy.py, src/qibo/models/circuit.py, src/qibo/tests/test_models_circuit_execution.py
This PR implements the following point:
from #720 and PR #799.
I will open a PR in qibolab to support this feature.
Checklist:
=> Accepting circuits as initial states

src/qibo/backends/abstract.py, src/qibo/backends/numpy.py, src/qibo/gates/channels.py, tests/test_gates_channels.py
Reverts qiboteam/qibo#819. I forgot this should be merged together with https://github.com/qiboteam/qibojit/pull/109 and just clicked on merge. I'm so sorry for this @scarrazza @AlejandroSopena.
=> Revert "Depolarizing channel"

doc/source/code-examples/examples.rst, src/qibo/gates/abstract.py, src/qibo/gates/channels.py, src/qibo/gates/gates.py, src/qibo/gates/measurements.py, src/qibo/gates/special.py, src/qibo/models/circuit.py, tests/test_gates_gates.py, tests/test_models_circuit.py, tests/test_models_circuit_qasm.py
Related to issue #850. This PR allows to change `name` parameter of `qibo.gates.Gate` and 2 other labels are added:
- `name`: label of the gate. Can be changed by a user.
- `draw_label`: a symbol for drawing a circuit. If `None` or empty, `gate.name[:4]` is used.
This parameter allows to remove `qibo.gates.DRAW_LABELS` dictionary.
- `@property qasm_label`: for gates supported by OpenQASM.
For example:
```python
from math import pi 
from qibo.models import Circuit
rx1 = gates.RX(0, pi/2)
rx1.name = "RX90"
rx1.draw_label = "RX1"
rx2 = gates.RX(1, 3 * pi/2)
rx2.name = "RX270"
rx2. draw_label = "RX2"
circuit = Circuit(2)
circuit.add(rx1)
circuit.add(rx2)
print(circuit.draw())
```
prints
```python
q0: ─RX1─
q1: ─RX2─
```
instead of 
```python
q0: ─RX─
q1: ─RX─
```
As …
=> Add gate labels

src/qibo/derivative.py, tests/test_derivative.py
In this PR a new feature has been added to the `parameter_shift` function. 
In this suggestion it accepts two more arguments: 
- `nshots`: if `None`, the simulation is executed, if not `None`, the `expectation_from_samples` function is called for calculating the expectation value of the target observable.
- `nruns`: since we have NISQ deivces, it can be useful to have a more stable estimation of the derivative. By setting `nruns`, one can decide to calculate the derivative as mean of `nruns` estimations.  
Checklist:
=> Hardware compatible parameter shift rule

src/qibo/optimizers.py
=> update bounds keyword docs for CMAES

src/qibo/models/evolution.py
Fixes #824. @MatteoRobbiati indeed you are right, it is a qibojit issue.
Checklist:
=> Copy ground state before passing to adiabatic evolution

src/qibo/backends/numpy.py, src/qibo/models/circuit.py, src/qibo/models/utils.py, tests/test_models_circuit.py
This PR fixes the circuit initialization requested in #720, with the deployment of the `initialize` and `eigenstate` inputs, that will add the gates to perform the basis changing of the initial state.
It follows a little example,
```python
circuit = Circuit(5, initialize="X", eigenstate="-")
print(circuit.draw())
```
@scarrazza what do you think about it ? 
Checklist:
=> circuit initialization

examples/anomaly_detection/README.md
As the article regarding quantum anomaly detection, on which this example is based, has been published i have added the reference at the beginning.
=> Add reference to anomaly detection example

src/qibo/models/error_mitigation.py
Fixes the error mitigation execution using `qibolab` backend.
=> Fix `noisy_circuit` in mitigation module

doc/source/api-reference/qibo.rst, doc/source/code-examples/advancedexamples.rst, src/qibo/models/error_mitigation.py, tests/test_models_error_mitigation.py
This PR implements two methods to mitigate readout errors. 
The first method involves estimating the columns of the calibration matrix by measuring the output frequencies  for all posible bit strings, and then applying its inverse to mitigate the noise.
The second method randomizes the circuit in such a way that it diagonalizes the measurement channel. This means that now the effect of readout noise on the expected value of a Pauli observable is a multiplicative factor.
An option to apply readout mitigation is added to all the error mitigation methods currently implemented.
Checklist:
=> Calibration matrix for readout mitigation

src/qibo/quantum_info/metrics.py, tests/test_quantum_info_metrics.py
=> Fix `test_entropy` for `cupy` backend

src/qibo/backends/numpy.py
This PR closes issue #917.
Checklist:
=> Fix repeated execution

doc/source/code-examples/advancedexamples.rst, src/qibo/models/circuit.py, tests/test_models_circuit.py, tests/test_models_circuit_features.py, tests/test_models_circuit_noise.py, tests/test_models_distcircuit.py
Since the `Circuit.with_noise` method works exclusively with `PauliNoiseChannel`, the method is better named as `Circuit.with_pauli_noise` in order to not create any confusion about using the method with other noise channels.
This was discussed in #898.
Checklist:
=> Rename `Circuit.with_noise` method as `Circuit.with_pauli_noise`

src/qibo/gates/channels.py, tests/test_gates_channels.py
=> Remove old channel initialisations and warnings

src/qibo/backends/numpy.py, tests/test_models_variational.py, tests/test_quantum_info_superoperator_transformations.py
Closes #928. 
This PR works with qiboteam/qibojit#125.
I've added an explicit cast to numpy array to make sure that this method works as expected also on GPU.
Checklist:
=> Fixing bug in `asmatrix_fused` with `CupyBackend`

doc/source/api-reference/qibo.rst, doc/source/code-examples/advancedexamples.rst, src/qibo/hamiltonians/hamiltonians.py, src/qibo/hamiltonians/models.py, tests/test_hamiltonians_symbolic.py
Fixes #935. Specifically:
* `nqubits` attribute was added to `SymbolicHamiltonian` as suggested in https://github.com/qiboteam/qibo/issues/935#issuecomment-1592312035. Note that the effect of this is still equivalent to padding, for example `SymbolicHamiltonian(Z(0) * Z(1), nqubits=4)` is equivalent to `SymbolicHamiltonian(Z(0) * Z(1) * I(2) * I(3))`.
* A `ValueError` is raised if there is a mismatch between the number of qubits in the state and the Hamiltonian in expectation value calculations.
* A documentation example about `expectation_from_samples` was added (@AlejandroSopena let me know if that is okay).
Checklist:
=> Fix `SymbolicHamiltonian.expectation` for different nqubits

doc/source/api-reference/qibo.rst, src/qibo/gates/gates.py, tests/test_gates_gates.py
This adds a delay option to the Align gate, also implementing the Align gate in qibocal's compiler.
Currently, the only way to add delays in circuit operations is via constructing a pulse sequence.
The delay option causes the circuit execution to pause for a specified period of time. This is currently done by sending a pulse of zero frequency and zero amplitude so that the control hardware performs the timing.
Please see the corresponding PR in qiboteam/qibolab#541.
Checklist:
=> Add delay pulse option to `Align` gate

src/qibo/callbacks.py, src/qibo/models/evolution.py
Fixes #973.
I am still puzzled about the `nqubit` setter in the `EntanglementEntropy` function. I think it works well if the callback is used in "circuit mode", but it doesn't if we track che entropy during an evolution. It seems to me is missing a step in which we calculate the number of qubits from the partition or from the hamiltonian. What do you think about it @stavros11?
I am testing the callbacks with the following script, if can help:
```python
import numpy as np
from qibo import models, callbacks, hamiltonians, gates, set_backend
set_backend("numpy")
nqubits = 2
T = 1
dt = 0.25
h0 = hamiltonians.X(2)
h1 = hamiltonians.TFIM(2)
c = models.Circuit(2)
c.add(gates.H(0))
c.add(gates.M(0,1))
callbacks_list = []
#callbacks_list.append(callbacks.EntanglementEntropy([0])) …
```
=> Fix double callbacks in evolution models

doc/source/appendix/citing-qibo.rst
The preprint at [https://arxiv.org/abs/2308.05657](https://arxiv.org/abs/2308.05657) is added to the docs.
=> Add qinntegrate paper to publications

src/qibo/backends/npmatrices.py
While I was looking through the code, I found this relic. I guess there is no reason to keep it there, since py3.7 is officially dead, and we do not support it since a while. 
This is just a minor simplification (just maintenance), and should change literally nothing in runtime operations (apart from parsing that code, importing `sys`, and make a trivial check... but they are all irrelevant operations...).
Checklist:
=> Drop cached property replacement

src/qibo/gates/abstract.py, tests/test_gates_abstract.py
Naive patch to save gates in RB implemented changes in https://github.com/qiboteam/qibocal/pull/412.
Checklist:
=> Save gates to JSON

src/qibo/backends/numpy.py, tests/test_measurements_probabilistic.py, tests/test_models_circuit_features.py, tests/test_models_circuit_noise.py
This PR fixes #1018 . There was an error in the way we were sampling the gates to apply when using the  `apply_channel()` method. This also affects the `PauliNoiseChannel` and the `UnitaryChannel`.
We did not notice earlier because the tests are also not implemented correctly. I will fix them as soon as possible.
Checklist:
=> Fix `apply_channel()` for statevector simulation

src/qibo/models/circuit.py, tests/test_models_circuit_execution.py
While doing some tests for #1022 I realized that `circuit.repeated_execution` was not updated properly when the `circuit.density_matrix` flag is switched after the gates are added. For example:
```py
circuit = Circuit(2)
circuit.add(gates.UnitaryChannel(...)) # circuit.repeated_execution is now switched to True because a channel is added
circuit.density_matrix = True # does not disable repeated execution
```
so in the end the circuit will be executed repeatedly even though we are using density matrices.
Here I changed `circuit.repeated_execution` to a property that is evaluated right before the circuit is executed and is `True` when the circuit contains collapse measurements or channels and density matrices are disabled.
Checklist:
=> Repeated execution and density matrices

src/qibo/gates/gates.py, tests/test_gates_gates.py
=> Add custom `decompose` method to `gates.U3` and `gates.CZ`

doc/source/api-reference/qibo.rst, src/qibo/backends/abstract.py, src/qibo/backends/numpy.py, src/qibo/backends/tensorflow.py, src/qibo/quantum_info/metrics.py, src/qibo/quantum_info/superoperator_transformations.py, src/qibo/quantum_info/utils.py, tests/test_callbacks.py, tests/test_gates_channels.py, tests/test_models_circuit_features.py, tests/test_quantum_info_metrics.py, tests/test_quantum_info_random.py
=> Add `order` parameter to `backend.calculate_norm`

src/qibo/backends/abstract.py, src/qibo/backends/numpy.py, src/qibo/callbacks.py, tests/test_callbacks.py
=> Implementation of `backend.calculate_overlap_density_matrix` in `numpy` backend

src/qibo/backends/abstract.py, src/qibo/backends/numpy.py, src/qibo/parallel.py, tests/test_parallel.py
Fixes #1021. I implemented a new parallel method for executing multiple circuits and exposed to the backends via `backend.execute_circuits`. I have not benchmarked this, as I am mostly interested in providing the interface for hardware, in order to use sequence unrolling (qiboteam/qibolab#618) with circuits, rather than the simulation method itself. It may be useful to have though.
Checklist:
=> Execute multiple circuits in parallel

src/qibo/backends/npmatrices.py
This closes #1073 and is needed for #1055 
Checklist:
=> Fix `matrix()` method for `gates.GeneralizedfSim`

src/qibo/models/double_bracket.py, tests/test_models_dbf.py
=> DBF Energy fluctuations

src/qibo/gates/gates.py, tests/test_gates_gates.py
=> Fix ``Clifford`` label on controlled gates

src/qibo/gates/gates.py, tests/test_gates_gates.py
Replacing decomposition of ECR gate for one that is composed of only Clifford gates
Checklist:
=> Change `gates.ECR` decomposition

src/qibo/gates/gates.py, tests/test_gates_gates.py
=> Add decomposition for ``gates.FSWAP``

src/qibo/models/variational.py, tests/test_models_variational.py
New feature in VQE. The energy fluctuation given the VQE hamiltonian $\hat{H}$ and a state $|\mu\rangle$:
$$\Xi_{k}(\mu) = \sqrt{\langle\mu|\hat{H}^2|\mu\rangle - \langle\mu|\hat{H}|\mu\rangle^2}.$$
Checklist:
=> Add energy fluctuation in VQE

.gitignore, src/qibo/result.py
=>  Fix `state(numpy=True)` method in ``QuantumState`` object

tests/test_models_encodings.py, tests/test_quantum_info_metrics.py, tests/test_quantum_info_random.py, tests/test_quantum_info_utils.py
=> Reduction of runtime for some tests

doc/source/code-examples/advancedexamples.rst, poetry.lock, pyproject.toml
I was debugging `doctest` when I realized that `testsetup` was not fixing the backend properly. I have changed this call to `testcode` and performance has improved a lot. We can reduce the requirements for examples (e.g. nqubits, epochs, shots) however the impact is not relevant in comparison to the small change applied in this branch.
Checklist:
=> increasing doctest speed

src/qibo/hamiltonians/hamiltonians.py
A very small fix (as the title says).
Checklist:
=> Return real expectation values in `Hamiltonian.expectation_from_samples`

src/qibo/models/dbi/double_bracket.py
=> use diagonal matrix with group commutator

doc/source/api-reference/qibo.rst, src/qibo/noise.py, src/qibo/quantum_info/metrics.py
=> Minor documentation fixes

doc/source/api-reference/qibo.rst, src/qibo/quantum_info/entropies.py, tests/test_quantum_info_entropies.py
=> Add `renyi_entropy` and `classical_renyi_entropy` to `quantum_info.entropies`

src/qibo/models/dbi/double_bracket.py, tests/test_models_dbi.py
This PR fixes tests after the discussion in #1154.
I decided to have the same behavior for `group_commutator` and `single_commutator`, i.e. when `d` is not provided the diagonal part of `h` will be used.
I've also fixed coverage.
Checklist:
=> Fixing DBI tests

doc/source/api-reference/qibo.rst, src/qibo/quantum_info/entropies.py, tests/test_quantum_info_entropies.py
=> Add `tsallis_entropy` and `classical_tsallis_entropy` to `quantum_info.entropies`

tests/test_derivative.py
Fixing #1181. 
Thanks @renatomello for raising the issue. Fixing the random generator seed should prevent such failed tests.
Checklist:
=> Fix `numpy.random` seed when testing Parameter Shift Rule.

src/qibo/models/error_mitigation.py
Fixes #1184. There was an issue when running the training circuits. I'm planning to update this part to use the `CliffordBackend` as soon as possible but for the moment, this fixes the tests.
Checklist:
=> GPU test fixing for error mitigation

src/qibo/backends/__init__.py, src/qibo/backends/clifford.py, src/qibo/gates/abstract.py, src/qibo/gates/channels.py, src/qibo/gates/special.py, src/qibo/hamiltonians/hamiltonians.py, src/qibo/models/circuit.py, src/qibo/models/error_mitigation.py, src/qibo/models/grover.py, src/qibo/models/hep.py, src/qibo/models/iqae.py, src/qibo/models/tsp.py, src/qibo/noise_model.py, src/qibo/optimizers.py, src/qibo/parallel.py, src/qibo/quantum_info/basis.py, src/qibo/quantum_info/metrics.py, src/qibo/quantum_info/quantum_networks.py, src/qibo/quantum_info/random_ensembles.py, src/qibo/quantum_info/superoperator_transformations.py, src/qibo/quantum_info/utils.py, src/qibo/result.py, src/qibo/transpiler/unitary_decompositions.py, tests/test_global_backend.py
This replaces all the repeated lines like:
```python3
if backend is None:  # pragma: no cover
backend = GlobalBackend()
```
by a function in `backends.__init__.py`
Checklist:
=> Move `GlobalBackend` check to `backends.__init__.py`

doc/source/conf.py
I've added the sphinx extension [viewcode](https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html) which allows to visualize the source code directly from the documentation.
After a quick discussion with @BrunoLiegiBastonLiegi we think that it would be useful to improve the quality of the documentation. 
If we like this approach I can propagate it to the other repos.
Checklist:
=> Add link to source code in the documentation

.github/workflows/publish.yml, README.md
Refactoring of README following https://github.com/qiboteam/qibolab/pull/788
Checklist:
=> Updating badges in README

src/qibo/backends/tensorflow.py
This follows a discussion in #1202 
Checklist:
=> Addition of parametrized gates missing in `TensorflowMatrices`

poetry.lock, pyproject.toml, src/qibo/backends/npmatrices.py
Store a backend agnostic matrix definition tht can be casted with a specific _cast function in the proper backend.
Necessary for PR #1202 
Checklist:
=> Backend-agnostic matrix definitions

tests/test_backends_clifford.py
=> Fix `cuquantum` test bug in `test_backends_clifford.py`

src/qibo/backends/__init__.py
=> Fix qibolab backend

doc/source/api-reference/qibo.rst, src/qibo/models/__init__.py, src/qibo/models/encodings.py, src/qibo/quantum_info/random_ensembles.py, tests/test_models_encodings.py
=> Add `entangling_layer` to `models.encodings`

doc/source/api-reference/qibo.rst
=> Standardize images in encoding documentation

poetry.lock, pyproject.toml
Small PR to restore the dependency to `qibojit/main` and `qibotn/main`.
Checklist:
=> Reverting `Qibojit` and `Qibotn` dependencies

doc/source/code-examples/advancedexamples.rst, src/qibo/backends/tensorflow.py, tests/test_models_circuit_backpropagation.py, tests/test_models_circuit_parametrized.py
=> Casting parameters as `float64` silencing `tf` warnings

src/qibo/backends/npmatrices.py, src/qibo/gates/gates.py, tests/test_gates_gates.py
Closes #1325
For simplicity I decided to pass only one qubit instead of multiple qubits.
There were some problems with `ParametrizedGate`.
Checklist:
=> Align as parametrized gate

src/qibo/quantum_info/random_ensembles.py
Related to the bug observed in https://github.com/qiboteam/qibo-client/issues/39. It looks like the qubit numbers are stored as numpy.int64 instead of python int, therefore serialization with json does not work from the qibo-client side. Could you please confirm this patch is acceptable?
Checklist:
=> random_clifford casting qubits to python int

src/qibo/optimizers.py, tests/test_models_variational.py
CMA callback fixed by calling it for each evaluation and not for each iteartion.
Should fix tests randomly failing, see #1344 for example.
Checklist:
=> Fix CMA callback

src/qibo/backends/numpy.py, src/qibo/optimizers.py, tests/test_models_variational.py
This PR proposes to speed up `circuit.unitary()` which returns the unitary corresponding to the circuit by performing the multiplication of all matrices gates using sparse matrices instead. I think that it makes sense given that most of times we are dealing with single and two qubit gates, which could be seen as sparse operators for large number of qubits.
Checklist:
=> Speed up `circuit.unitary()` using sparse matrices

src/qibo/backends/numpy.py, src/qibo/optimizers.py, tests/test_models_variational.py
Enabling the callback usage also with SGD optimizers.
Checklist:
=> Add callback to SGD and CMA-ES optimizer

src/qibo/quantum_info/entropies.py, tests/test_callbacks.py
The Von Neumann entropy function when return_spectrum=True returns -log(eigenvalues). However, if the state is pure, return_spectrum=True returned 1.0 which is the value of the eigenvalue, not the -log. The function is now changed to return 0.0 to be more consistent with the behavior of the function in the pure case.
Checklist:
=> Fix value of the spectrum returned in the `quantum_info.entropies.von_neumann_entropy`

src/qibo/hamiltonians/adiabatic.py, src/qibo/hamiltonians/hamiltonians.py, tests/test_hamiltonians_trotter.py
Fixes #1357. 
I believe the `TrotterCircuit` class is implementing a cache of the circuit implementing the Trotter decomposition returned by `hamiltonian.circuit(dt)` , to avoid recreating it if the users decides to use a different `dt`. However, this creates a ("secret") link between the circuits returned by `hamiltonian.circuit` that can confuse users, such as in #1357, and also complicates the code.
If allocating a circuit is not considered very costly, this cache probably does not provide much in terms of performance, therefore I decided to remove it to have cleaner code (and behavior).
Checklist:
=> Remove `TrotterCircuit` cache

src/qibo/backends/abstract.py, src/qibo/backends/numpy.py, src/qibo/gates/abstract.py, src/qibo/gates/gates.py, src/qibo/models/circuit.py, tests/test_backends.py, tests/test_gates_gates.py, tests/test_models_circuit_features.py
This closes #1279 and #1354
Checklist:
=> Fix `Gate.matrix` and `Circuit.unitary` in the presence of `Gate.controlled_by` method

doc/source/api-reference/qibo.rst, src/qibo/quantum_info/__init__.py, src/qibo/quantum_info/operations.py, tests/test_quantum_info_operations.py
=> Addition of linear algebra `operations` submodule to `quantum_info` module

src/qibo/models/error_mitigation.py, src/qibo/transpiler/pipeline.py, src/qibo/transpiler/placer.py, src/qibo/transpiler/router.py, src/qibo/transpiler/unroller.py, tests/test_transpiler_pipeline.py, tests/test_transpiler_placer.py, tests/test_transpiler_router.py, tests/test_transpiler_unroller.py
Solve bugs in #1363 and #1318 
Checklist:
=> Fix transpiler bugs about moved measurements and duplicated gates

src/qibo/models/encodings.py, tests/test_models_encodings.py
=> Allow `Circuit` `kwargs` in `models.encodings`

src/qibo/hamiltonians/hamiltonians.py, tests/test_hamiltonians_symbolic.py
=> Symbolic Hamiltonian with constants

src/qibo/backends/clifford.py
This PR fixes a `TypeError` when using noise channels in Clifford circuits and running them with the `CliffordBackend` on GPU. It can be reproduced with the following code extracted from  [test_backends_clifford.py](https://github.com/qiboteam/qibo/blob/master/tests/test_backends_clifford.py):
```Python
import numpy as np
from qibo.backends import CliffordBackend
from qibo.quantum_info import random_clifford
from qibo.noise import NoiseModel, PauliError
backend = CliffordBackend('cupy')
nqubits = 3
c = random_clifford(nqubits, density_matrix=True, backend=backend)
noise = NoiseModel()
noisy_gates = np.random.choice(c.queue, size=1, replace=False)
noise.add(PauliError([("X", 0.3)]), noisy_gates[0].__class__)
c.add(gates.M(*range(nqubits)))
c = noise.apply(c)
result = …
```
=> Apply channel for Clifford circuits with `cupy`

src/qibo/gates/gates.py
=> Adjusting clifford condition in GPI2

doc/source/code-examples/tutorials/dbi/dbi_cost_functions.ipynb, doc/source/code-examples/tutorials/dbi/dbi_gradient_descent_strategies.ipynb, doc/source/code-examples/tutorials/dbi/dbi_group_commutator_tests.ipynb, doc/source/code-examples/tutorials/dbi/dbi_scheduling.ipynb, doc/source/code-examples/tutorials/dbi/dbi_strategies_compare.ipynb, doc/source/code-examples/tutorials/dbi/dbi_strategy_Ising_model.ipynb, doc/source/code-examples/tutorials/dbi/dbi_strategy_Pauli-Z.ipynb
In this PR I aim to reduce the warnings got compiling the documentation.
Not exactly addressing #1228 but related.
Checklist:
=> Reduce docs compilation warnings

poetry.lock, pyproject.toml
=> Adding qulacs to extra

src/qibo/result.py
This should fix #1412, however I am not sure if it causes any other issues as I don't understand why this `cast` was introduced and the workflows are failing for other reasons.
Checklist:
=> Fix complex samples

src/qibo/backends/numpy.py, src/qibo/measurements.py, src/qibo/result.py
The root cause of the issue raised in #1412 was a `cast` to `numpy` inside `NumpyBackend.samples_to_binary`. That is what was turning the subsequent `cast` into a requirement for `torch`. Without the former, the latter could be removed.
Checklist:
=> Fix root cause of bug reported in PR #1412

src/qibo/transpiler/decompositions.py, src/qibo/transpiler/unroller.py, tests/test_transpiler_unroller.py
This covers issue #1421.
Checklist:
=> Add `gates.CNOT` as a native gate in gate decomposition

doc/source/api-reference/qibo.rst, src/qibo/derivative.py, src/qibo/hamiltonians/abstract.py, src/qibo/hamiltonians/hamiltonians.py, src/qibo/hamiltonians/models.py, src/qibo/symbols.py
Improved documentation of the modules mentioned in the title + a faster implementation of the `multikron` helper function defined inside the `Hamiltonian` module.
Checklist:
=> Improved docs of `Hamiltonian` and `Gradients` modules

src/qibo/backends/clifford.py, src/qibo/gates/abstract.py, src/qibo/gates/measurements.py, src/qibo/measurements.py, src/qibo/quantum_info/clifford.py, src/qibo/result.py, tests/test_measurements.py, tests/test_states.py
This addresses the bug #1426 by implementing a proper serialization of measurement gates and their result.
Furthermore, the possibility to specify the `basis` of measurement gates with strings (for instance `"Z"` or `["X", "Z", "Y"]`) has been added.
I also made some minor modifications to `MeasurementResult`, and I would also like to remove the `circuit` attribute from it. At the moment it is only used to generate the samples when they are not available. However, as I see it, the `MeasurementResult` should always be associated with the samples.
Checklist:
=> Serialization of measurements

doc/source/code-examples/examples.rst, src/qibo/ui/mpldrawer.py
Thanks @sergiomtzlosa for the fixes already done in #1438. We can keep that PR to solve the coverage problems and use this one to fix asap the errors.
Checklist:
=> Fixes related to MPL drawer

doc/source/api-reference/qibo.rst, src/qibo/gates/channels.py, src/qibo/quantum_info/basis.py, src/qibo/quantum_info/entropies.py, src/qibo/quantum_info/superoperator_transformations.py, src/qibo/ui/mpldrawer.py
=> Fix math rendering in some docsstrings of the `quantum_info` module

doc/source/api-reference/qibo.rst, src/qibo/backends/abstract.py, src/qibo/backends/clifford.py, src/qibo/gates/measurements.py, src/qibo/models/error_mitigation.py, src/qibo/quantum_info/clifford.py, src/qibo/result.py, src/qibo/ui/mpldrawer.py
This closes almost all warnings in the docs that are not already being closed by #1441.
Checklist:
=> Fix doc warnings

examples/shor/functions.py
Fix Shor example, which is outdated since #1039, as reported in #1432.
The measurement in the end is needed because it is no longer possible to execute circuits that contain only collapse measurements using state vectors.
Specifying `nshots=1` is needed because a default `nshots=1000` was introduced in #1039 compared to the `None` being used before. This was also causing the performance issue reported in #1432, because during the repeated execution it was executing the circuit 1000 times instead of one that we need.
Checklist:
=> Fix Shor example

src/qibo/quantum_info/superoperator_transformations.py
Closes #1445 
This bug somehow was introduced by #1276, but the fix is just to swap the order of two lines.
Checklist:
=> Fix bug in `quantum_info._reshuffling`

src/qibo/quantum_info/metrics.py, tests/test_quantum_info_metrics.py
Two different definitions of fidelity were being mixed, one with $\text{Tr}$ and another with $\text{Tr}^{2}$. This PR fixes it.
Checklist:
=> Fix definition of `fidelity` in `quantum_info.metrics`

doc/source/api-reference/qibo.rst, src/qibo/quantum_info/entropies.py, tests/test_quantum_info_entropies.py
=> Add `classical_tsallis_relative_entropy` to `quantum_info.entropies`

src/qibo/gates/measurements.py, src/qibo/measurements.py, tests/test_measurements.py, tests/test_states.py
This should close #1433
Checklist:
=> Remove circular dependency between `MeasurementResult` and `M` gate

doc/source/api-reference/qibo.rst, pyproject.toml, src/qibo/quantum_info/linalg_operations.py, tests/test_quantum_info_operations.py
Needs to be merged before #1456 
Checklist:
=> Add `partial_transpose` to `quantum_info.linalg_operations`

doc/source/api-reference/qibo.rst, src/qibo/backends/abstract.py, src/qibo/backends/numpy.py, src/qibo/backends/pytorch.py, src/qibo/backends/tensorflow.py, src/qibo/quantum_info/linalg_operations.py, src/qibo/quantum_info/superoperator_transformations.py, tests/test_quantum_info_operations.py, tests/test_quantum_info_superoperator_transformations.py
This is needed in #1471 
Checklist:
=> Add `calculate_singular_value_decompositon` as a backend method

.pre-commit-config.yaml
The hook is one of the default ones, and essentially for free. It will mainly help keeping `pyproject.toml` formatted.
Checklist:
=> Add hook to check toml files

src/qibo/gates/abstract.py
This avoids the `try/except` for controlled gates in `from_dict` when the gate is a measurement. Should close #1482. 
Checklist:
=> Skipping controlled `try/except` for `M` gate in `from_dict`

src/qibo/backends/__init__.py
As they may also be part of a backend search loop.
Checklist:
=> Avoid logging for missing backends

doc/source/api-reference/qibo.rst, src/qibo/backends/abstract.py, src/qibo/backends/numpy.py, src/qibo/backends/pytorch.py, src/qibo/backends/tensorflow.py, src/qibo/quantum_info/metrics.py, tests/test_quantum_info_metrics.py
=> Add `quantum_fisher_information_matrix` to `quantum_info.metrics`

doc/source/api-reference/qibo.rst, src/qibo/models/encodings.py, tests/test_models_encodings.py
=> Add `GHZ` circuit function

src/qibo/transpiler/unroller.py, tests/test_transpiler_unroller.py
`Unroller` generates an error when initialized with unsupported gates.
https://github.com/qiboteam/qibolab/actions/runs/11569426877/job/32203123767?pr=1083#step:10:259
In this PR, when qibo receives native gates, unsupported gates will be ignored. Should we require backends to match qibo’s native gate set?
Checklist:
https://github.com/qiboteam/qibolab/pull/1083
=> Unsupported native gates

src/qibo/backends/__init__.py
The name of the `i`th hardware qubit is stored at index `i` in `QibolabBackend.qubits`. When passed to current qibo implementation, this is then converted to `q{i}` and stored in `initial_layout`. 
This PR ensures that the keys in `initial_layout` (the hardware qubit names) are sorted during default transpilation, so `i` in `gate.qubits` in transpiled circuit consistently refers to the `i`th hardware qubit.
Will be deprecated after #1500.
Checklist:
=> Temporary fix for `q{i}` mapping

src/qibo/hamiltonians/hamiltonians.py, tests/test_hamiltonians_symbolic.py
=> Fix bug in `SymbolicHamiltonian.__mul__`

src/qibo/ui/mpldrawer.py
This should address #1536 
Checklist:
=> `qibo.ui` import of `matplotlib.pyplot`

doc/source/api-reference/qibo.rst, pyproject.toml, src/qibo/hamiltonians/__init__.py, src/qibo/hamiltonians/models.py, tests/test_hamiltonians_models.py
=> Add general `Heisenberg` Hamiltonian and `XXX` model

src/qibo/backends/__init__.py, tests/test_backends_global.py
I was trying to execute the following snippet:
```py
from qibo import set_backend
from qibo import gates, Circuit
set_backend("qibolab", platform="qw5q_platinum")
c = Circuit(3, wire_names = [1, 3, 2])
c.add(gates.GPI2(0,0))
c.add(gates.GPI2(1,0))
c.add(gates.GPI2(2,0))
c.add(gates.M(0,1,2))
r = c()
print(r.frequencies())
```
With the following error:
```
2024-12-11 14:48:38,615 - qm - INFO     - Starting session: 649d66cf-f564-4ac9-bd72-086b8ef0b602
[Qibo 0.2.15|INFO|2024-12-11 14:48:38]: Loading platform qw5q_platinum
[Qibo 0.2.15|INFO|2024-12-11 14:48:38]: Using qibolab (qw5q_platinum) backend on /CPU:0
[Qibo 0.2.15|ERROR|2024-12-11 14:48:38]: The circuit qubits are not in the connectivity graph.
Traceback (most recent call last):
File "/nfs/users/edoardo.pedicillo/circuit.py", line …
```
=> Graph not built if no edges are provided

src/qibo/models/circuit.py
=> Fix documentation of `models.circuit.Circuit`

src/qibo/gates/gates.py, src/qibo/transpiler/decompositions.py, tests/test_gates_gates.py
=> Add decomposition for `gates.CRY`

src/qibo/models/_openqasm.py, tests/test_models_circuit_qasm.py
=> Fix bug in `qasm` parser when `gates.U3` is present.

doc/source/code-examples/advancedexamples.rst, src/qibo/tomography/gate_set_tomography.py, tests/test_tomography_gate_set_tomography.py
=> Updating GST to accept parameterised gates

src/qibo/transpiler/abstract.py, src/qibo/transpiler/asserts.py, src/qibo/transpiler/pipeline.py, src/qibo/transpiler/router.py
=> Improving docstrings in final qubit mapping, w/ `{logical: physical}`

doc/source/api-reference/qibo.rst, src/qibo/models/__init__.py, src/qibo/models/encodings.py, tests/test_models_encodings.py
[Reference](https://arxiv.org/abs/2405.20408)
Checklist:
=> Add `hamming_weight_encoder` to `models.encodings`

src/qibo/transpiler/placer.py, src/qibo/transpiler/router.py, tests/test_transpiler_placer.py, tests/test_transpiler_router.py
=> Fix `StarConnectivtyPlacer/Router._check_star_connectivity` for `len(nodes)>5`

src/qibo/models/encodings.py, tests/test_models_encodings.py
Data is amplitude-encoded in the lexicographical order instead of the order of the original Gray code.
Checklist:
=> Modify `models.encodings.hamming_weight_encoder` to upload data in the lexicographical order

src/qibo/gates/gates.py
=> Fix docstring of `gates.PRX`

poetry.lock, pyproject.toml, src/qibo/backends/npmatrices.py, src/qibo/transpiler/unitary_decompositions.py, tests/test_backends.py, tests/test_transpiler_unitary_decompositions.py
Sync with https://github.com/qiboteam/qibojit/pull/202 which updates the cuquantum version
=> Updating cuquantum version

src/qibo/models/circuit.py, tests/test_models_circuit.py
As per title this fixes the serialization of circuit by including the ``wire_names``, should fix the problems encountered in qiboteam/qibo-client#99.
Checklist:
=> Adding ``wire_names`` to ``circuit.raw`` and ``from_dict``

selfhosted
This is done in order to avoid possible problems with ``qibojit`` selfhosted tests that were writing to the same ``/tmp/tests`` directory.
Checklist:
=> Changed the directory to selfhosted tests to ``$(mktemp -d)``

selfhosted, tests/conftest.py
Same as qiboteam/qibojit#206. A ``--gpu-only`` option is added to pytest to run tests on GPU backends only.
Checklist:
=> Selfhosted GPU tests restricted to GPU backends only

src/qibo/backends/npmatrices.py, src/qibo/gates/gates.py, tests/test_gates_gates.py
The  `gates.GeneralizedRBS` gate must be Hamming weight preserving when the number of input and output qubits is the same, but here we can see that it is not: 
```Python
from qibo.backends import NumpyBackend
backend = NumpyBackend()
gate = gates.GeneralizedRBS([1,2],[3,4],theta=0.123)
print(gate.matrix(backend))
```
It is mixing states $|0001\rangle$ and $|0110\rangle$ .
This PR address this issue. I construct the RBS gate without considering the order of the qubits passed as input. This is the same approach we follow for other multi-qubit gates. 
This simplifies the code and makes the cheat introduced in PR #1594 unnecessary.
Checklist:
=> Matrix representation of `gates.GeneralizedRBS` independent of qubit order

src/qibo/ui/mpldrawer.py
Checklist:
The clustering action for the circuit is useful on more than 2-qubits, this review skip the clustering for 1-qubit circuits
=> Fix clustering bug when plotting single-qubit circuits

src/qibo/ui/mpldrawer.py
Checklist:
Now by using the `wire_names` property from circuit it is possible to set the label to the mpl circuit:
```
circuit = Circuit(2)
circuit.add(gates.X(0))
circuit.add(gates.X(1))
circuit.add(gates.M(0, 1))
circuit.wire_names = ["w_1", "w_2"]
plot_circuit(circuit)
```
=> custom labels for plot_circuit drawing function - issue #1611

src/qibo/ui/mpldrawer.py
Checklist:
The circuit does not print with odd number of qubits, like 5, 7 and so on, because the circuit is using out of bounds number of qubits
```python
from qibo.ui import plot_circuit
from qibo.models.hep import qPDF
ansatz = 'Weighted'
multi_output = True
layers = 3
nqubits = 7
mypdf = qPDF(ansatz, layers, nqubits, multi_output=multi_output)
plot_circuit(mypdf.circuit, scale = 0.8, cluster_gates = True, style="quantumspain")
```
=> review plot out of bounds qubit number - bug #1497

src/qibo/hamiltonians/hamiltonians.py, tests/test_hamiltonians.py
Small fix to ``expectation_from_samples`` that selects only the elements of the diagonal that correspond to non-zero counts.
Checklist:
=> ``expectation_from_samples`` fix

src/qibo/backends/npmatrices.py, src/qibo/hamiltonians/hamiltonians.py, src/qibo/models/error_mitigation.py
As per title, this introduces the use of a simulation backend (numpy for now) to get the noise free values for data-based mitigation methods, such as CDR.
Checklist:
=> Fix to data-based mitigation methods

doc/source/api-reference/qibo.rst, src/qibo/models/__init__.py, src/qibo/models/encodings.py, src/qibo/quantum_info/utils.py, tests/test_models_encodings.py, tests/test_quantum_info_utils.py
Here, I have three contributions:
- `permutation_synthesis`: as the name suggests we synthesize a quantum circuit given a permutation description following the procedure described in [[1](https://arxiv.org/abs/2406.16142)]
- for this, I needed `decompose_permutation`, which, given a permutation sigma on {0,...,d-1} and a power‑of‑two budget `m`, decompose sigma into the fewest layers sigma_1, sigma_2, ..., sigma_t such that
- each layer has at most m disjoint transpositions
- each layer moves a power‑of‑two number of indices.
- We do this as follows:
1) Cycle extraction – split sigma into disjoint cycles.
2) Star factorisation – a k‑cycle becomes (k-1) hub–spoke swaps.
3) Greedy packing – merge swaps into layers while keeping rules.
With a permutation synthesis at hand, it is possible to …
=> Permutation synthesis and Li's sparse encoder
