src/qibo/tensorflow/callbacks.py
src/qibo/tests/test_callbacks.py

Entanglement spectrum

---

README.md
examples/adiabatic3sat/README.md
examples/benchmarks/results/ADIABATIC.md
examples/benchmarks/results/HARDWARE.md
examples/benchmarks/results/PRECISION.md

changing documentation urls from latest to stable

---

examples/EF_QAE/README.md
examples/EF_QAE/main.py

Here I fix some missing if/elif/else for the new ef example.

Fixing tests for examples

---

.github/workflows/wheels.yml
requirements.txt

Upgrading to tf 2.4.1 and removing the range stored in our requirements, given that we do not test for older versions.

upgrading to tf 2.4.1

---

src/qibo/abstractions/callbacks.py
src/qibo/backends/abstract.py
src/qibo/backends/numpy.py
src/qibo/core/callbacks.py
src/qibo/tests_new/test_backends_agreement.py
src/qibo/tests_new/test_core_callbacks.py
src/qibo/tests_new/test_core_gates.py

Fixes #324 by going to the next eigenenergy if the gap is zero (`< EIGVAL_CUTOFF` for precision reasons). If this happens a warning is raised. I also moved `test_callbacks.py` to the new tests and enabled testing with the numpy backends.

Fix gap callback for degenerate Hamiltonians

---

src/qibo/abstractions/circuit.py

Fixes #333. @igres26 thanks for reporting this issue, could you please retry your code with this PR and confirm this fixes the issue?

Fixing circuit.draw misalignment

---

src/qibo/backends/tensorflow.py
src/qibo/config.py
src/qibo/tests_new/test_measurement_gate_probabilistic.py

Adds threshold on nshots for selecting the measurement frequency algorithm.

Add nshot switcher

---

src/qibo/abstractions/abstract_gates.py
src/qibo/abstractions/circuit.py
src/qibo/abstractions/gates.py
src/qibo/tests_new/test_abstract_circuit.py
src/qibo/tests_new/test_abstract_gates.py
src/qibo/tests_new/test_core_circuit_features.py

Fixes #348. I added some tests that cover the problematic case but it would be good to also extensively test the example of @igres26 before merging this.

Fix `.on_qubits()` with `.controlled_by()` gates

---

doc/source/hep.rst

Fixing import issue for sphinx compilation.

fixing hep import in sphinx

---

doc/source/contributing.rst

This PR includes a new section in the docs explaining how to compile locally and extend it.

documentation instructions

---

src/qibo/backends/__init__.py
src/qibo/backends/tensorflow.py

A quick module parsing for the backend activations.
@stavros11 please let me know if you agree.

backends auto-discovery

---

src/qibo/core/hamiltonians.py
src/qibo/tests/test_hamiltonians.py

Fixes #408 by adding support for complex coefficients in symbolic (sympy) Hamiltonians.

Complex numbers in sympy Hamiltonians

---

.github/workflows/rules.yml
.github/workflows/wheels.yml
doc/source/installation.rst
src/qibo/parallel.py
src/qibo/tests/test_models_variational.py
src/qibo/tests/test_parallel.py

Minor changes concerning qibotf installation from source.

updating qibotf docs

---

doc/source/applications.rst

Following our discussion this PR includes minor adjustments to the applications presentation.
@igres26 @AdrianPerezSalinas could you please confirm everything makes sense?

fixing topics for applications

---

src/qibo/abstractions/abstract_gates.py
src/qibo/abstractions/callbacks.py
src/qibo/abstractions/circuit.py
src/qibo/backends/abstract.py
src/qibo/backends/numpy.py
src/qibo/backends/tensorflow.py
src/qibo/core/callbacks.py
src/qibo/core/circuit.py
src/qibo/core/distcircuit.py
src/qibo/core/distutils.py
src/qibo/core/gates.py
src/qibo/core/states.py
src/qibo/core/terms.py
src/qibo/tests/test_abstract_callbacks.py
src/qibo/tests/test_abstract_gates.py
src/qibo/tests/test_core_gates.py
src/qibo/tests/test_core_gates_density_matrix.py
src/qibo/tests/test_core_gates_features.py
src/qibo/tests/test_models_evolution.py

Performs minimal refactoring following the discussion in #447.
@stavros11 let me know if you agree.

gates refactor

---

src/qibo/backends/__init__.py
src/qibo/backends/numpy.py

Implements the fix proposed in #459.
@stavros11 please have a look, I dislike this extra operation only for numpy, we could add a threshold or apply the normalization conditionally.

normalizing probs

---

doc/source/qibo.rst

Removes a duplicated class in the documentation

Minor fix in the documentation

---

src/qibo/abstractions/circuit.py

drawing Unitary gates

---

.github/workflows/deploy.yml
docker/dockerfile

This implements a simple docker image with qibo installed for each specific tag version.
Here an example for the 0.1.5 release: https://github.com/qiboteam/qibo/pkgs/container/qibo

adding docker images for tags

---

doc/source/developer-guides/general.rst
setup.py
src/qibo/__init__.py
src/qibo/backends/__init__.py
src/qibo/backends/profiles.yml
src/qibo/backends/tensorflow.py
src/qibo/config.py
src/qibo/tests/test_backends_init.py

check minimum version for backends

---

doc/source/getting-started/installation.rst

The conda instructions for qibo and qibojit were swapped. I also updated the instructions for qibojit, given that now it depends on qibo.

Minor fixes in the docs

---

README.md
doc/source/appendix/citing-qibo.rst
doc/source/conf.py
doc/source/index.rst

Updates docs, includes a new page for publications/citation instructions.

add citing qibo page in docs

---

src/qibo/tests/test_measurements.py

Fix for the failing tests mentioned in #622.

Fix test failing on GPU

---

src/qibo/tests/test_models_tsp.py
src/qibo/tests/test_models_variational.py

Hopefully CI will pass with this. 
After some quick tests it seems that the final parameters found by the BFGS optimization are slightly different for tensorflow which causes the final state to also be slightly different. If I fix the final parameters then the final states agree. I am still not sure what is causing the discrepancy in optimization.

Add atol in TSP test

---

.github/workflows/rules.yml

start workflow with label

---

doc/source/api-reference/qibo.rst

Fix doc bug from automodule to autofunction

---

doc/source/conf.py
src/qibo/__init__.py

I have modified the `conf.py` in the doc folder selecting the Furo sphinx theme and setting the colors according to the web site.
When we are ready with the site we can merge this branch.

From Standard to Furo doc's theme

---

doc/source/api-reference/qibo.rst
src/qibo/gates/gates.py

added documentation for RXX RYY and RZZ gates
Checklist:

Fix documentation

---

src/qibo/gates/channels.py

This PR implements a fix for the first issue raised in #718
Checklist:

Depolarizing channel: backend agnostic

---

examples/vqregressor/README.md

Now the "code here" link in the vqregressor example is correct.

Update vqregressor link in README.md

---

doc/source/api-reference/qibo.rst
src/qibo/derivative.py
src/qibo/tests/test_derivative.py

in this PR, the description of the `derivative` module has been added to the documentation.

Add derivative to qibo docs

---

src/qibo/models/variational.py

Checklist:
Including the relevant references and more examples of how the loss functions of QAOA can be called.

including more documentation of the loss functions for QAOA.

---

src/qibo/quantum_info/basis.py
src/qibo/tests/test_quantum_info_basis.py

Generalization of pauli_basis() to all vectorization() orders

---

src/qibo/models/error_mitigation.py
src/qibo/tests/test_models_error_mitigation.py

Implemented a fix for a little bug present in #768. 
Added tests with 1 qubit circuits for ZNE and vnCDR.
Checklist:

fixed insertion gate bug + added 1 qubit tests

---

.github/workflows/deploy.yml
.github/workflows/rules.yml
pyproject.toml
pytest.ini
src/qibo/backends/numpy.py
src/qibo/hamiltonians/adiabatic.py
src/qibo/hamiltonians/hamiltonians.py
src/qibo/models/circuit.py
src/qibo/models/error_mitigation.py

This PR modify the workflows in order to use the ones stored in `qiboteam/workflows` (see qiboteam/workflows#23).
Checklist:

Workflow migration

---

examples/test_examples.py
setup.py

cleanup setup with unused module

---

src/qibo/backends/numpy.py
src/qibo/gates/channels.py
src/qibo/quantum_info/metrics.py
src/qibo/quantum_info/random_ensembles.py
src/qibo/quantum_info/superoperator_transformations.py
src/qibo/quantum_info/utils.py
src/qibo/symbols.py
src/qibo/tests/test_callbacks.py
src/qibo/tests/test_cirq.py
src/qibo/tests/test_gates_channels.py
src/qibo/tests/test_gates_density_matrix.py
src/qibo/tests/test_gates_gates.py
src/qibo/tests/test_gates_special.py
src/qibo/tests/test_hamiltonians.py
src/qibo/tests/test_hamiltonians_from_symbols.py
src/qibo/tests/test_hamiltonians_terms.py
src/qibo/tests/test_hamiltonians_trotter.py
src/qibo/tests/test_measurements_collapse.py
src/qibo/tests/test_models_circuit_execution.py
src/qibo/tests/test_models_distcircuit_execution.py
src/qibo/tests/test_models_qft.py
src/qibo/tests/test_models_variational.py
src/qibo/tests/test_noise.py
src/qibo/tests/test_quantum_info_superoperator_transformations.py
src/qibo/tests/utils.py

Fix bug in `KrausChannel.to_choi()` + remove multiple `DeprecationWarning` from tests

---

src/qibo/models/circuit.py

This PR has been opened in order to fix #793.
Checklist:

update circuit docs

---

src/qibo/backends/abstract.py
src/qibo/backends/numpy.py
src/qibo/gates/channels.py
tests/test_gates_channels.py

Depolarizing Channel

---

.github/workflows/publish.yml

This PR fixes #818.
Checklist:

add poetry-extras input

---

doc/source/api-reference/qibo.rst
src/qibo/quantum_info/metrics.py
src/qibo/quantum_info/superoperator_transformations.py
tests/test_gates_channels.py
tests/test_quantum_info_superoperator_transformations.py

Pauli-Liouville transformations

---

src/qibo/backends/numpy.py
src/qibo/gates/channels.py
tests/test_gates_channels.py

`to_choi` for Reset and ThermalRelaxation

---

src/qibo/quantum_info/basis.py
src/qibo/quantum_info/random_ensembles.py
src/qibo/quantum_info/superoperator_transformations.py
tests/test_quantum_info_basis.py
tests/test_quantum_info_superoperator_transformations.py

Add sparse representation to `quantum_info.basis`

---

doc/source/appendix/citing-qibo.rst

In this PR some publications based on `qibo` are added to the appendix.
Checklist:

Based on qibo section in docs appendix

---

doc/source/api-reference/qibo.rst
src/qibo/quantum_info/superoperator_transformations.py
tests/test_quantum_info_superoperator_transformations.py

Chi-matrix representation

---

doc/source/api-reference/qibo.rst
src/qibo/gates/channels.py
src/qibo/quantum_info/utils.py
tests/test_noise.py
tests/test_quantum_info_utils.py

Hamming weight function

---

doc/source/api-reference/qibo.rst
src/qibo/quantum_info/random_ensembles.py
tests/test_quantum_info_random.py

`random_quantum_channel` function

---

src/qibo/backends/numpy.py
src/qibo/gates/channels.py
src/qibo/quantum_info/basis.py
src/qibo/quantum_info/metrics.py
src/qibo/quantum_info/random_ensembles.py
src/qibo/quantum_info/superoperator_transformations.py
src/qibo/quantum_info/utils.py
tests/test_callbacks.py
tests/test_cirq.py
tests/test_gates_channels.py
tests/test_gates_density_matrix.py
tests/test_gates_gates.py
tests/test_quantum_info_basis.py
tests/test_quantum_info_metrics.py
tests/test_quantum_info_random.py
tests/test_quantum_info_superoperator_transformations.py
tests/test_quantum_info_utils.py

backend-agnostic quantum info module

---

src/qibo/states.py

Closes #666. I prefer to just update the documentation, otherwise we have to introduce a new attribute to the Circuit class and complicate the code just to raise a warning.
Checklist:

add docs to noisy circuit probabilities

---

doc/source/api-reference/qibo.rst
src/qibo/quantum_info/random_ensembles.py
tests/test_quantum_info_random.py

`basis` flag in `random_density_matrix`

---

src/qibo/quantum_info/random_ensembles.py
tests/test_gates_special.py
tests/test_hamiltonians_terms.py
tests/test_hamiltonians_trotter.py
tests/test_measurements_collapse.py
tests/test_models_distcircuit_execution.py
tests/test_models_qft.py
tests/test_models_variational.py
tests/test_quantum_info_metrics.py
tests/test_quantum_info_random.py
tests/test_states.py

Modify quantum_info tests

---

src/qibo/derivative.py
tests/test_derivative.py

Fix `test_derivative.py` for `cupy` backend

---

src/qibo/backends/__init__.py

Add `H`, `S`, `SDG`, and `CNOT` to `QiboMatrices`

---

src/qibo/gates/channels.py

`DepolarizingChannel` inherits `PauliNoiseChannel`

---

src/qibo/gates/channels.py
tests/test_gates_channels.py

This PR closes issue #885
Checklist:

`ThermalRelaxationChannel` fix for `cupy` backend

---

src/qibo/backends/abstract.py
src/qibo/derivative.py
src/qibo/noise.py
src/qibo/quantum_info/superoperator_transformations.py

Fix `sphinx` errors and warnings

---

src/qibo/models/utils.py
src/qibo/models/variational.py
tests/test_models_variational.py

Checklist:
Previously, when we want to optimize our QAOA, the loss functions are fixed to be either expectation, cvar, and gibbs function. This PR aims to make an investigation of loss functions more convenient.  That is an investigator can now customize their loss function, pass in their own customized loss function with their parameters.

Generalize qaoa loss function

---

doc/source/api-reference/qibo.rst
src/qibo/models/circuit.py
src/qibo/quantum_info/basis.py
src/qibo/quantum_info/metrics.py
src/qibo/quantum_info/random_ensembles.py
src/qibo/quantum_info/superoperator_transformations.py
src/qibo/quantum_info/utils.py

This implements minor improvements in the documentation of the `quantum_info` module, and also closes #898 
Checklist:

Minor improvements to `quantum_info` documentation

---

src/qibo/gates/channels.py
src/qibo/quantum_info/basis.py
src/qibo/quantum_info/random_ensembles.py
src/qibo/quantum_info/superoperator_transformations.py
tests/test_gates_channels.py
tests/test_quantum_info_basis.py
tests/test_quantum_info_random.py
tests/test_quantum_info_superoperator_transformations.py

Add elements order to `pauli_basis`

---

.github/workflows/deploy.yml
.github/workflows/publish.yml
.github/workflows/rules.yml

adding tests for python3.11

---

doc/source/api-reference/qibo.rst
src/qibo/quantum_info/metrics.py
tests/test_quantum_info_basis.py
tests/test_quantum_info_metrics.py

Add `bures_angle` and `bures_distance` to `quantum_info.metrics`

---

doc/source/api-reference/qibo.rst
src/qibo/quantum_info/metrics.py
tests/test_quantum_info_metrics.py

Add `entanglement_entropy` to `quantum_info.metrics`

---

doc/source/api-reference/qibo.rst
src/qibo/quantum_info/metrics.py
tests/test_quantum_info_metrics.py

Add `impurity`, `infidelity`, and `process_infidelity` to `quantum_info.metrics`

---

src/qibo/backends/numpy.py
src/qibo/quantum_info/metrics.py
tests/test_quantum_info_metrics.py
tests/test_quantum_info_utils.py

`quantum_info.metrics.fidelity` generalized for mixed states

---

tests/test_quantum_info_metrics.py

Fix test in `master` branch

---

src/qibo/backends/__init__.py
src/qibo/quantum_info/random_ensembles.py
src/qibo/quantum_info/utils.py
tests/test_quantum_info_random.py

Generalize `quantum_info.random_clifford` to `n` qubits

---

doc/source/api-reference/qibo.rst
src/qibo/gates/channels.py
src/qibo/quantum_info/metrics.py
src/qibo/quantum_info/superoperator_transformations.py
tests/test_quantum_info_superoperator_transformations.py

Functions to convert channels to superoperator representations

---

examples/EF_QAE/main.py
examples/anomaly_detection/test.py
examples/anomaly_detection/train.py
examples/variational_classifier/main.py

This is just a small update to the code, as i was revisiting it. Unfortunately i have found problems in loading data from different folders, i will open an issue about this, as it regards also other examples.

anomaly detection example update

---

src/qibo/backends/npmatrices.py
src/qibo/gates/gates.py
tests/test_gates_gates.py

Generalizaton of the `MS` gate

---

src/qibo/gates/abstract.py
src/qibo/gates/channels.py
src/qibo/gates/gates.py
tests/test_gates_gates.py

New `unitary` attribute to gates and `KrausChannel` checks if all operators are unitaries

---

poetry.lock
pyproject.toml

Update `qibojit` on `poetry.lock`

---

src/qibo/gates/abstract.py
src/qibo/models/circuit.py

Fixes #956. In the previous meeting we decided to leave the current behavior and only update the documentation.
Checklist:

Update docs for dagger

---

src/qibo/quantum_info/utils.py

Fix `hadamard_transform` documentation

---

doc/source/api-reference/qibo.rst
src/qibo/quantum_info/metrics.py
src/qibo/quantum_info/random_ensembles.py
src/qibo/quantum_info/superoperator_transformations.py
src/qibo/quantum_info/utils.py

Improvements to `quantum_info` documentation

---

src/qibo/models/circuit.py
tests/test_models_circuit_qasm.py

fix issue 1004

---

doc/source/appendix/citing-qibo.rst

Add reference to qibosoq paper

---

doc/source/api-reference/qibo.rst
src/qibo/parameter.py

- A small fix to the `Parameter` docstrings;
- added description into API docs.

Parameter docs 

---

doc/source/api-reference/qibo.rst
src/qibo/backends/npmatrices.py
src/qibo/gates/gates.py
tests/test_gates_gates.py

Rename `gates.RXY` as `gates.RXXYY` and fix `gates.SYC` docstring

---

poetry.lock

updating lock file

---

doc/source/api-reference/qibo.rst
examples/mvc/README.md
src/qibo/gates/special.py

Fix sphinx compilation warnings/errors

---

src/qibo/backends/numpy.py
src/qibo/result.py
tests/test_callbacks.py
tests/test_models_circuit_execution.py
tests/test_models_circuit_features.py
tests/test_result.py

Minor modifications on top of #1039 needed for the qibojit and qibolab backends.
Checklist:

Circuit Execution Output bugfix for the qibojit and qibolab backends

---

src/qibo/backends/__init__.py

Inclusion of all cached gate matrices into ``QiboMatrices``

---

doc/source/getting-started/backends.rst

Note in the docs as decided in #1037.
Checklist:

Add note about in-place updating in the docs

---

src/qibo/quantum_info/metrics.py
tests/test_quantum_info_metrics.py

Add `seed` parameter to `quantum_info.entangling_capacity`

---

tests/test_backends_clifford.py
tests/test_measurements.py
tests/test_quantum_info_random.py
tests/test_transpiler_blocks.py

Fix test failing and remove unnecessary prints from tests

---

src/qibo/quantum_info/entropies.py
tests/test_quantum_info_entropies.py

Add `classical_relative_entropy` to `quantum_info.entropies`

---

doc/source/api-reference/qibo.rst
src/qibo/quantum_info/entanglement.py
src/qibo/quantum_info/entropies.py
tests/test_quantum_info_entropies.py

Add (quantum) `relative_entropy` to `quantum_info.entropies`

---

src/qibo/backends/__init__.py

Needed for qiboteam/qibolab#784
Checklist:

Remove runcard argument from set_backend

---

doc/source/appendix/citing-qibo.rst

Adding qibolab doi

---

src/qibo/quantum_info/random_ensembles.py

Minor fix to `quantum_info.random_ensembles.random_clifford` docstring

---

src/qibo/quantum_info/random_ensembles.py

Small fix to math rendering in docs

---

poetry.lock
pyproject.toml

Fixing missing dependencies

---

.github/workflows/rules.yml

Testing CI on PR opened

---

src/qibo/transpiler/pipeline.py

Fix transpiler bug

---

src/qibo/quantum_info/utils.py

The distance being reported before was not correct. This fix it.
Checklist:

Fix to logic in `quantum_info.hamming_distance`

---

examples/reuploading_classifier/datasets.py
examples/variational_classifier/qclassifier.py
src/qibo/models/qcnn.py
src/qibo/noise_model.py
src/qibo/transpiler/blocks.py
src/qibo/transpiler/pipeline.py
src/qibo/transpiler/placer.py
tests/test_gates_gates.py
tests/test_models_dbi.py
tests/test_quantum_info_superoperator_transformations.py
tests/test_transpiler_blocks.py

Small `lint` improvements

---

.github/workflows/deploy.yml
.github/workflows/publish.yml
.github/workflows/rules.yml
.github/workflows/selfhosted.yml

Switch reusable workflows to v1, instead of main

---

README.md

Adding contact mail

---

src/qibo/transpiler/router.py
tests/test_transpiler_router.py

This PR addresses the issue #1396.
Checklist:

Fix Looping Behavior in Qibo SABRE

---

src/qibo/backends/__init__.py
tests/conftest.py

Extract just the fix from #1425 (but not the complex and failing test).

Fix default backend loading

---

src/qibo/backends/_clifford_operations.py
src/qibo/quantum_info/clifford.py

Bugfix to matrix unpacking in `CliffordBackend`

---

src/qibo/quantum_info/utils.py

Fix math rendering.
Checklist:

Fix docstring of `quantum_info.utils.total_variation_distance`

---

src/qibo/backends/abstract.py
src/qibo/backends/numpy.py
src/qibo/backends/pytorch.py
src/qibo/backends/tensorflow.py
src/qibo/quantum_info/entanglement.py
src/qibo/quantum_info/entropies.py
src/qibo/quantum_info/linalg_operations.py
tests/test_quantum_info_entropies.py
tests/test_quantum_info_operations.py

Fix bug in `quantum_info.linalg_operations.matrix_power` for negative powers of singular matrices

---

src/qibo/transpiler/decompositions.py

`gates.RBS` decomposition with less gates

---

doc/source/code-examples/advancedexamples.rst

Fix import in Advanced Examples

---

src/qibo/hamiltonians/hamiltonians.py
tests/test_hamiltonians.py
tests/test_hamiltonians_symbolic.py

Minor bug fix to expectation_from_samples

---

src/qibo/transpiler/asserts.py
tests/test_transpiler_placer.py
tests/test_transpiler_router.py

Tests introduced in #1567 are failing in the `master` branch because the external PR did not trigger tests properly.
This is blocking the workflow in other PRs.
Checklist:

Fix transpiler tests failing in the `master` branch

---

src/qibo/backends/__init__.py

Include `T` gate in `qibo.matrices`

---

src/qibo/gates/gates.py
src/qibo/models/error_mitigation.py

Remove while loop in `error_sensitive_circuit`

---

src/qibo/gates/gates.py
tests/test_gates_gates.py

This is needed in #1591 
Checklist:

Fix `gates.GeneralizedRBS.apply` method

---

poetry.lock
pyproject.toml

Since qiboteam/qibojit#214 has just been merged.

Use `qibojit` `main` for tests

---

src/qibo/gates/abstract.py

Remove outdated comments in `gates.abstract.Gate` class

---

src/qibo/backends/abstract.py
src/qibo/backends/numpy.py
src/qibo/hamiltonians/hamiltonians.py
tests/test_hamiltonians.py

Remove unnecessary backend methods

---

doc/source/api-reference/qibo.rst
src/qibo/models/encodings.py
tests/test_models_encodings.py

Closes #1655 
Implemented Dicke State generation with all-to-all connectivity option. I see @AlejandroSopena implemented the first part already, should I adapt the second part to extend his?
Checklist:

[UnitaryHack2025] Implement all-to-all and simple Dicke State generation circuits

---

src/qibo/hamiltonians/hamiltonians.py

Casting expectation values to real in `expectation_from_samples`

---

src/qibo/gates/gates.py
src/qibo/transpiler/decompositions.py
src/qibo/transpiler/unroller.py
tests/test_gates_abstract.py

Per title. Fixes bug raised in the Discussion #1669.
Checklist:

Enable `TOFFOLI.decompose` and add `CCZ` decomposition into native gate set that includes the `CZ` gate

---

src/qibo/optimizers.py

Adding `_check_backend` to CMA optimizer

---

src/qibo/ui/result_visualization.py

Small fix to ``visualize_state``

---

doc/source/api-reference/qibo.rst
src/qibo/hamiltonians/__init__.py
src/qibo/hamiltonians/models.py
tests/test_hamiltonians_models.py

Add `LABS` Hamiltonian

---

src/qibo/gates/abstract.py
src/qibo/gates/gates.py
tests/test_gates_gates.py

This is just a first prototype for adding gradients which can be computed analytically for certain gates.
They are currently used in https://github.com/qiboteam/qiboml/pull/147

Adding gradients required for adjoint differentiation

---

poetry.lock
pyproject.toml

I forgot to update the `qibojit` branch in the `pyproject.toml` before merging #1698. This fixes that.
Checklist:

Update `qibojit` branch

---

src/qibo/gates/abstract.py
src/qibo/gates/gates.py
src/qibo/transpiler/decompositions.py

Closes #1720 and #1720 
Checklist:

Fix `GeneralizedRBS` decomposition + optimize `RBS` decomposition according to number of controls
